// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/force-c/nai-tizi/kratos/application/sys-api/internal/biz"
	"github.com/force-c/nai-tizi/kratos/application/sys-api/internal/conf"
	"github.com/force-c/nai-tizi/kratos/application/sys-api/internal/data"
	"github.com/force-c/nai-tizi/kratos/application/sys-api/internal/server"
	"github.com/force-c/nai-tizi/kratos/application/sys-api/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/go-kratos/kratos/v2/transport/http"
)

// Injectors from wire.go:

func wireApp(cfg *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	repositories, cleanup, err := newRepositories(cfg)
	if err != nil {
		return nil, nil, err
	}
	usecases := biz.NewUsecases(repositories)
	webSocketHub, cleanup2, err := newWebSocketHub()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	gatewayDeps := newGatewayDeps(repositories, usecases, webSocketHub)
	services := service.NewServices(usecases)
	server := newHTTPServer(cfg, gatewayDeps, services)
	app := newApp(logger, server)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func newRepositories(cfg *conf.Bootstrap) (*data.Repositories, func(), error) {
	repos, err := data.NewRepositories(cfg.Server.RPC)
	if err != nil {
		return nil, nil, err
	}
	return repos, func() {
		_ = repos.Close()
	}, nil
}

func newWebSocketHub() (*server.WebSocketHub, func(), error) {
	hub := server.NewWebSocketHub()
	return hub, func() {
		hub.Stop()
	}, nil
}

func newGatewayDeps(repos *data.Repositories, usecases *biz.Usecases, wsHub *server.WebSocketHub) *server.GatewayDeps {
	return &server.GatewayDeps{Auth: repos.Auth, Attachment: usecases.Attachment, OperLog: repos.OperLog, WebSocket: wsHub}
}

func newHTTPServer(cfg *conf.Bootstrap, deps *server.GatewayDeps, services *service.Services) *http.Server {
	return server.NewHTTPServer(
		cfg.Server.HTTP,
		deps,
		services.Health,
		services.Auth,
		services.Captcha,
		services.Menu,
		services.User,
		services.Role,
		services.Org,
		services.Config,
		services.Dict,
		services.LoginLog,
		services.OperLog,
		services.StorageEnv,
		services.Attachment,
	)
}

func newApp(logger log.Logger, httpSrv *http.Server) *kratos.App {
	return kratos.New(kratos.Name("sys-api"), kratos.Logger(logger), kratos.Server(httpSrv))
}
