// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: application/sys-rpc/internal/conf/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Registry      *Registry              `protobuf:"bytes,2,opt,name=registry,proto3" json:"registry,omitempty"`
	Auth          *Auth                  `protobuf:"bytes,3,opt,name=auth,proto3" json:"auth,omitempty"`
	Jwt           *JWT                   `protobuf:"bytes,4,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Data          *Data                  `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
	Observability *Observability         `protobuf:"bytes,6,opt,name=observability,proto3" json:"observability,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetRegistry() *Registry {
	if x != nil {
		return x.Registry
	}
	return nil
}

func (x *Bootstrap) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Bootstrap) GetJwt() *JWT {
	if x != nil {
		return x.Jwt
	}
	return nil
}

func (x *Bootstrap) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Bootstrap) GetObservability() *Observability {
	if x != nil {
		return x.Observability
	}
	return nil
}

type Auth struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AllowConcurrent bool                   `protobuf:"varint,1,opt,name=allowConcurrent,proto3" json:"allowConcurrent,omitempty"`
	ShareToken      bool                   `protobuf:"varint,2,opt,name=shareToken,proto3" json:"shareToken,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Auth) GetAllowConcurrent() bool {
	if x != nil {
		return x.AllowConcurrent
	}
	return false
}

func (x *Auth) GetShareToken() bool {
	if x != nil {
		return x.ShareToken
	}
	return false
}

type JWT struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Secret        string                 `protobuf:"bytes,1,opt,name=secret,proto3" json:"secret,omitempty"`
	Expire        int64                  `protobuf:"varint,2,opt,name=expire,proto3" json:"expire,omitempty"`
	Issuer        string                 `protobuf:"bytes,3,opt,name=issuer,proto3" json:"issuer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JWT) Reset() {
	*x = JWT{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JWT) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JWT) ProtoMessage() {}

func (x *JWT) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JWT.ProtoReflect.Descriptor instead.
func (*JWT) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{2}
}

func (x *JWT) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *JWT) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *JWT) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type Server struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grpc          *GRPC                  `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{3}
}

func (x *Server) GetGrpc() *GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

type Registry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Driver        string                 `protobuf:"bytes,2,opt,name=driver,proto3" json:"driver,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Namespace     string                 `protobuf:"bytes,4,opt,name=namespace,proto3" json:"namespace,omitempty"`
	RegisterTTL   string                 `protobuf:"bytes,5,opt,name=registerTTL,proto3" json:"registerTTL,omitempty"`
	Etcd          *RegistryEtcd          `protobuf:"bytes,6,opt,name=etcd,proto3" json:"etcd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registry) Reset() {
	*x = Registry{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registry) ProtoMessage() {}

func (x *Registry) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registry.ProtoReflect.Descriptor instead.
func (*Registry) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Registry) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *Registry) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Registry) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Registry) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Registry) GetRegisterTTL() string {
	if x != nil {
		return x.RegisterTTL
	}
	return ""
}

func (x *Registry) GetEtcd() *RegistryEtcd {
	if x != nil {
		return x.Etcd
	}
	return nil
}

type RegistryEtcd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []string               `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Timeout       string                 `protobuf:"bytes,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistryEtcd) Reset() {
	*x = RegistryEtcd{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistryEtcd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistryEtcd) ProtoMessage() {}

func (x *RegistryEtcd) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistryEtcd.ProtoReflect.Descriptor instead.
func (*RegistryEtcd) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{5}
}

func (x *RegistryEtcd) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *RegistryEtcd) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegistryEtcd) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistryEtcd) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       string                 `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GRPC) Reset() {
	*x = GRPC{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GRPC) ProtoMessage() {}

func (x *GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GRPC.ProtoReflect.Descriptor instead.
func (*GRPC) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{6}
}

func (x *GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *GRPC) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Database      *Database              `protobuf:"bytes,1,opt,name=database,proto3" json:"database,omitempty"`
	Redis         *Redis                 `protobuf:"bytes,2,opt,name=redis,proto3" json:"redis,omitempty"`
	Wechat        *WeChat                `protobuf:"bytes,3,opt,name=wechat,proto3" json:"wechat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Data) Reset() {
	*x = Data{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{7}
}

func (x *Data) GetDatabase() *Database {
	if x != nil {
		return x.Database
	}
	return nil
}

func (x *Data) GetRedis() *Redis {
	if x != nil {
		return x.Redis
	}
	return nil
}

func (x *Data) GetWechat() *WeChat {
	if x != nil {
		return x.Wechat
	}
	return nil
}

type Database struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        string                 `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	Dsn           string                 `protobuf:"bytes,2,opt,name=dsn,proto3" json:"dsn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Database) Reset() {
	*x = Database{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{8}
}

func (x *Database) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Database) GetDsn() string {
	if x != nil {
		return x.Dsn
	}
	return ""
}

type Redis struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Db            int32                  `protobuf:"varint,3,opt,name=db,proto3" json:"db,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Redis) Reset() {
	*x = Redis{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Redis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Redis) ProtoMessage() {}

func (x *Redis) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Redis.ProtoReflect.Descriptor instead.
func (*Redis) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{9}
}

func (x *Redis) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Redis) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Redis) GetDb() int32 {
	if x != nil {
		return x.Db
	}
	return 0
}

type WeChat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=appId,proto3" json:"appId,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	Timeout       string                 `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeChat) Reset() {
	*x = WeChat{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeChat) ProtoMessage() {}

func (x *WeChat) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeChat.ProtoReflect.Descriptor instead.
func (*WeChat) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{10}
}

func (x *WeChat) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *WeChat) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *WeChat) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

type Observability struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DbSlowThresholdMs    int64                  `protobuf:"varint,1,opt,name=dbSlowThresholdMs,proto3" json:"dbSlowThresholdMs,omitempty"`
	RedisSlowThresholdMs int64                  `protobuf:"varint,2,opt,name=redisSlowThresholdMs,proto3" json:"redisSlowThresholdMs,omitempty"`
	DbPoolSampleInterval string                 `protobuf:"bytes,3,opt,name=dbPoolSampleInterval,proto3" json:"dbPoolSampleInterval,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Observability) Reset() {
	*x = Observability{}
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observability) ProtoMessage() {}

func (x *Observability) ProtoReflect() protoreflect.Message {
	mi := &file_application_sys_rpc_internal_conf_conf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observability.ProtoReflect.Descriptor instead.
func (*Observability) Descriptor() ([]byte, []int) {
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP(), []int{11}
}

func (x *Observability) GetDbSlowThresholdMs() int64 {
	if x != nil {
		return x.DbSlowThresholdMs
	}
	return 0
}

func (x *Observability) GetRedisSlowThresholdMs() int64 {
	if x != nil {
		return x.RedisSlowThresholdMs
	}
	return 0
}

func (x *Observability) GetDbPoolSampleInterval() string {
	if x != nil {
		return x.DbPoolSampleInterval
	}
	return ""
}

var File_application_sys_rpc_internal_conf_conf_proto protoreflect.FileDescriptor

const file_application_sys_rpc_internal_conf_conf_proto_rawDesc = "" +
	"\n" +
	",application/sys-rpc/internal/conf/conf.proto\x12\x12kratos.conf.sysrpc\"\xc9\x02\n" +
	"\tBootstrap\x122\n" +
	"\x06server\x18\x01 \x01(\v2\x1a.kratos.conf.sysrpc.ServerR\x06server\x128\n" +
	"\bregistry\x18\x02 \x01(\v2\x1c.kratos.conf.sysrpc.RegistryR\bregistry\x12,\n" +
	"\x04auth\x18\x03 \x01(\v2\x18.kratos.conf.sysrpc.AuthR\x04auth\x12)\n" +
	"\x03jwt\x18\x04 \x01(\v2\x17.kratos.conf.sysrpc.JWTR\x03jwt\x12,\n" +
	"\x04data\x18\x05 \x01(\v2\x18.kratos.conf.sysrpc.DataR\x04data\x12G\n" +
	"\robservability\x18\x06 \x01(\v2!.kratos.conf.sysrpc.ObservabilityR\robservability\"P\n" +
	"\x04Auth\x12(\n" +
	"\x0fallowConcurrent\x18\x01 \x01(\bR\x0fallowConcurrent\x12\x1e\n" +
	"\n" +
	"shareToken\x18\x02 \x01(\bR\n" +
	"shareToken\"M\n" +
	"\x03JWT\x12\x16\n" +
	"\x06secret\x18\x01 \x01(\tR\x06secret\x12\x16\n" +
	"\x06expire\x18\x02 \x01(\x03R\x06expire\x12\x16\n" +
	"\x06issuer\x18\x03 \x01(\tR\x06issuer\"6\n" +
	"\x06Server\x12,\n" +
	"\x04grpc\x18\x01 \x01(\v2\x18.kratos.conf.sysrpc.GRPCR\x04grpc\"\xc6\x01\n" +
	"\bRegistry\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x16\n" +
	"\x06driver\x18\x02 \x01(\tR\x06driver\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1c\n" +
	"\tnamespace\x18\x04 \x01(\tR\tnamespace\x12 \n" +
	"\vregisterTTL\x18\x05 \x01(\tR\vregisterTTL\x124\n" +
	"\x04etcd\x18\x06 \x01(\v2 .kratos.conf.sysrpc.RegistryEtcdR\x04etcd\"~\n" +
	"\fRegistryEtcd\x12\x1c\n" +
	"\tendpoints\x18\x01 \x03(\tR\tendpoints\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x18\n" +
	"\atimeout\x18\x04 \x01(\tR\atimeout\"N\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\tR\atimeout\"\xa5\x01\n" +
	"\x04Data\x128\n" +
	"\bdatabase\x18\x01 \x01(\v2\x1c.kratos.conf.sysrpc.DatabaseR\bdatabase\x12/\n" +
	"\x05redis\x18\x02 \x01(\v2\x19.kratos.conf.sysrpc.RedisR\x05redis\x122\n" +
	"\x06wechat\x18\x03 \x01(\v2\x1a.kratos.conf.sysrpc.WeChatR\x06wechat\"4\n" +
	"\bDatabase\x12\x16\n" +
	"\x06driver\x18\x01 \x01(\tR\x06driver\x12\x10\n" +
	"\x03dsn\x18\x02 \x01(\tR\x03dsn\"G\n" +
	"\x05Redis\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x0e\n" +
	"\x02db\x18\x03 \x01(\x05R\x02db\"P\n" +
	"\x06WeChat\x12\x14\n" +
	"\x05appId\x18\x01 \x01(\tR\x05appId\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\tR\atimeout\"\xa5\x01\n" +
	"\rObservability\x12,\n" +
	"\x11dbSlowThresholdMs\x18\x01 \x01(\x03R\x11dbSlowThresholdMs\x122\n" +
	"\x14redisSlowThresholdMs\x18\x02 \x01(\x03R\x14redisSlowThresholdMs\x122\n" +
	"\x14dbPoolSampleInterval\x18\x03 \x01(\tR\x14dbPoolSampleIntervalBMZKgithub.com/gcc798/quick.admin/kratos/application/sys-rpc/internal/conf;confb\x06proto3"

var (
	file_application_sys_rpc_internal_conf_conf_proto_rawDescOnce sync.Once
	file_application_sys_rpc_internal_conf_conf_proto_rawDescData []byte
)

func file_application_sys_rpc_internal_conf_conf_proto_rawDescGZIP() []byte {
	file_application_sys_rpc_internal_conf_conf_proto_rawDescOnce.Do(func() {
		file_application_sys_rpc_internal_conf_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_sys_rpc_internal_conf_conf_proto_rawDesc), len(file_application_sys_rpc_internal_conf_conf_proto_rawDesc)))
	})
	return file_application_sys_rpc_internal_conf_conf_proto_rawDescData
}

var file_application_sys_rpc_internal_conf_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_application_sys_rpc_internal_conf_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),     // 0: kratos.conf.sysrpc.Bootstrap
	(*Auth)(nil),          // 1: kratos.conf.sysrpc.Auth
	(*JWT)(nil),           // 2: kratos.conf.sysrpc.JWT
	(*Server)(nil),        // 3: kratos.conf.sysrpc.Server
	(*Registry)(nil),      // 4: kratos.conf.sysrpc.Registry
	(*RegistryEtcd)(nil),  // 5: kratos.conf.sysrpc.RegistryEtcd
	(*GRPC)(nil),          // 6: kratos.conf.sysrpc.GRPC
	(*Data)(nil),          // 7: kratos.conf.sysrpc.Data
	(*Database)(nil),      // 8: kratos.conf.sysrpc.Database
	(*Redis)(nil),         // 9: kratos.conf.sysrpc.Redis
	(*WeChat)(nil),        // 10: kratos.conf.sysrpc.WeChat
	(*Observability)(nil), // 11: kratos.conf.sysrpc.Observability
}
var file_application_sys_rpc_internal_conf_conf_proto_depIdxs = []int32{
	3,  // 0: kratos.conf.sysrpc.Bootstrap.server:type_name -> kratos.conf.sysrpc.Server
	4,  // 1: kratos.conf.sysrpc.Bootstrap.registry:type_name -> kratos.conf.sysrpc.Registry
	1,  // 2: kratos.conf.sysrpc.Bootstrap.auth:type_name -> kratos.conf.sysrpc.Auth
	2,  // 3: kratos.conf.sysrpc.Bootstrap.jwt:type_name -> kratos.conf.sysrpc.JWT
	7,  // 4: kratos.conf.sysrpc.Bootstrap.data:type_name -> kratos.conf.sysrpc.Data
	11, // 5: kratos.conf.sysrpc.Bootstrap.observability:type_name -> kratos.conf.sysrpc.Observability
	6,  // 6: kratos.conf.sysrpc.Server.grpc:type_name -> kratos.conf.sysrpc.GRPC
	5,  // 7: kratos.conf.sysrpc.Registry.etcd:type_name -> kratos.conf.sysrpc.RegistryEtcd
	8,  // 8: kratos.conf.sysrpc.Data.database:type_name -> kratos.conf.sysrpc.Database
	9,  // 9: kratos.conf.sysrpc.Data.redis:type_name -> kratos.conf.sysrpc.Redis
	10, // 10: kratos.conf.sysrpc.Data.wechat:type_name -> kratos.conf.sysrpc.WeChat
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_application_sys_rpc_internal_conf_conf_proto_init() }
func file_application_sys_rpc_internal_conf_conf_proto_init() {
	if File_application_sys_rpc_internal_conf_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_sys_rpc_internal_conf_conf_proto_rawDesc), len(file_application_sys_rpc_internal_conf_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_application_sys_rpc_internal_conf_conf_proto_goTypes,
		DependencyIndexes: file_application_sys_rpc_internal_conf_conf_proto_depIdxs,
		MessageInfos:      file_application_sys_rpc_internal_conf_conf_proto_msgTypes,
	}.Build()
	File_application_sys_rpc_internal_conf_conf_proto = out.File
	file_application_sys_rpc_internal_conf_conf_proto_goTypes = nil
	file_application_sys_rpc_internal_conf_conf_proto_depIdxs = nil
}
