// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/gcc798/nai-tizi/kratos/application/sys-rpc/ent/predicate"
	"github.com/gcc798/nai-tizi/kratos/application/sys-rpc/ent/storageenv"
)

// StorageEnvDelete is the builder for deleting a StorageEnv entity.
type StorageEnvDelete struct {
	config
	hooks    []Hook
	mutation *StorageEnvMutation
}

// Where appends a list predicates to the StorageEnvDelete builder.
func (_d *StorageEnvDelete) Where(ps ...predicate.StorageEnv) *StorageEnvDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *StorageEnvDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StorageEnvDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *StorageEnvDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(storageenv.Table, sqlgraph.NewFieldSpec(storageenv.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// StorageEnvDeleteOne is the builder for deleting a single StorageEnv entity.
type StorageEnvDeleteOne struct {
	_d *StorageEnvDelete
}

// Where appends a list predicates to the StorageEnvDelete builder.
func (_d *StorageEnvDeleteOne) Where(ps ...predicate.StorageEnv) *StorageEnvDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *StorageEnvDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{storageenv.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *StorageEnvDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
