// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type ApiPermissionAssignReq struct {
	PermissionIds []int64 `json:"permissionIds"`
}

type ApiPermissionSaveReq struct {
	ParentId int64  `json:"parentId,optional"`
	Module   string `json:"module"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	NodeType int64  `json:"nodeType,optional"`
	Action   string `json:"action"`
	Method   string `json:"method,optional"`
	Path     string `json:"path,optional"`
	Sort     int64  `json:"sort,optional"`
	Status   int64  `json:"status,optional"`
	Remark   string `json:"remark,optional"`
}

type ApiPermissionUpdateReq struct {
	Id       int64  `path:"id"`
	ParentId int64  `json:"parentId,optional"`
	Module   string `json:"module"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	NodeType int64  `json:"nodeType,optional"`
	Action   string `json:"action"`
	Method   string `json:"method,optional"`
	Path     string `json:"path,optional"`
	Sort     int64  `json:"sort,optional"`
	Status   int64  `json:"status,optional"`
	Remark   string `json:"remark,optional"`
}

type AssignRoleReq struct {
	UserId int64 `json:"userId"`
	RoleId int64 `json:"roleId"`
}

type AttachmentBindReq struct {
	AttachmentId  int64                  `path:"attachmentId"`
	BusinessType  string                 `json:"businessType"`
	BusinessId    string                 `json:"businessId"`
	BusinessField string                 `json:"businessField,optional"`
	IsPublic      bool                   `json:"isPublic,optional"`
	Metadata      map[string]interface{} `json:"metadata,optional"`
	ExpireTime    string                 `json:"expireTime,optional"`
}

type AttachmentBusinessQueryReq struct {
	BusinessType string `form:"businessType"`
	BusinessId   string `form:"businessId"`
}

type AttachmentIdPathReq struct {
	AttachmentId int64 `path:"attachmentId"`
}

type AttachmentPageReq struct {
	PageNum      int64  `json:"pageNum"`
	PageSize     int64  `json:"pageSize"`
	FileName     string `json:"fileName,optional"`
	FileType     string `json:"fileType,optional"`
	BusinessType string `json:"businessType,optional"`
}

type AttachmentUploadReq struct {
	EnvCode string `form:"envCode,optional"`
}

type AttachmentUrlQueryReq struct {
	AttachmentId int64 `path:"attachmentId"`
	Expires      int64 `form:"expires,optional"`
}

type BatchIdsReq struct {
	Ids []int64 `json:"ids"`
}

type CaptchaEmailReq struct {
	Email string `json:"email"`
}

type CaptchaPhoneReq struct {
	Phonenumber string `json:"phonenumber"`
}

type CommonResp struct {
	Code int         `json:"code"`
	Msg  string      `json:"msg"`
	Data interface{} `json:"data,optional"`
}

type ConfigCodeQueryReq struct {
	Code string `form:"code"`
}

type ConfigCreateReq struct {
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	Data     interface{} `json:"data,optional"`
	Remark   string      `json:"remark,optional"`
	CreateBy int64       `json:"createBy"`
	UpdateBy int64       `json:"updateBy"`
}

type ConfigPageReq struct {
	PageNum  int64  `json:"pageNum,optional"`
	PageSize int64  `json:"pageSize,optional"`
	Name     string `json:"name,optional"`
	Code     string `json:"code,optional"`
}

type ConfigUpdateReq struct {
	Id       int64       `path:"id"`
	Name     string      `json:"name"`
	Code     string      `json:"code"`
	Data     interface{} `json:"data,optional"`
	Remark   string      `json:"remark,optional"`
	UpdateBy int64       `json:"updateBy"`
}

type DictCreateReq struct {
	ParentId  int64  `json:"parentId,optional"`
	DictType  string `json:"dictType"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	Sort      int64  `json:"sort,optional"`
	IsDefault bool   `json:"isDefault,optional"`
	Status    int64  `json:"status,optional"`
	Remark    string `json:"remark,optional"`
	CreateBy  int64  `json:"createBy,optional"`
	UpdateBy  int64  `json:"updateBy,optional"`
}

type DictLabelQueryReq struct {
	DictType  string `form:"dictType"`
	DictValue string `form:"dictValue"`
}

type DictPageReq struct {
	PageNum   int64  `json:"pageNum,optional"`
	PageSize  int64  `json:"pageSize,optional"`
	DictType  string `json:"dictType,optional"`
	DictLabel string `json:"dictLabel,optional"`
	Status    int64  `json:"status,optional"`
}

type DictTypeQueryReq struct {
	DictType string `form:"dictType"`
	ParentId int64  `form:"parentId,optional"`
}

type DictUpdateReq struct {
	Id        int64  `path:"id"`
	ParentId  int64  `json:"parentId,optional"`
	DictType  string `json:"dictType"`
	DictLabel string `json:"dictLabel"`
	DictValue string `json:"dictValue"`
	Sort      int64  `json:"sort,optional"`
	IsDefault bool   `json:"isDefault,optional"`
	Status    int64  `json:"status,optional"`
	Remark    string `json:"remark,optional"`
	UpdateBy  int64  `json:"updateBy,optional"`
}

type IdPathReq struct {
	Id int64 `path:"id"`
}

type LogCleanReq struct {
	Days int64 `json:"days"`
}

type LoginLogPageReq struct {
	PageNum   int64  `json:"pageNum,optional"`
	PageSize  int64  `json:"pageSize,optional"`
	UserName  string `json:"userName,optional"`
	Ipaddr    string `json:"ipaddr,optional"`
	Status    int64  `json:"status,optional"`
	StartTime string `json:"startTime,optional"`
	EndTime   string `json:"endTime,optional"`
}

type LoginLogReq struct {
	UserName      string `json:"userName"`
	Ipaddr        string `json:"ipaddr,optional"`
	LoginLocation string `json:"loginLocation,optional"`
	Browser       string `json:"browser,optional"`
	Os            string `json:"os,optional"`
	Status        int64  `json:"status,optional"`
	Msg           string `json:"msg,optional"`
	ClientId      string `json:"clientId,optional"`
}

type LoginLogUpdateReq struct {
	Id            int64  `path:"id"`
	UserName      string `json:"userName,optional"`
	Ipaddr        string `json:"ipaddr,optional"`
	LoginLocation string `json:"loginLocation,optional"`
	Browser       string `json:"browser,optional"`
	Os            string `json:"os,optional"`
	Status        int64  `json:"status,optional"`
	Msg           string `json:"msg,optional"`
	ClientId      string `json:"clientId,optional"`
}

type LoginReq struct {
	ClientKey    string `json:"clientKey"`
	ClientSecret string `json:"clientSecret"`
	GrantType    string `json:"grantType"`
	Username     string `json:"username,optional"`
	Password     string `json:"password,optional"`
	Code         string `json:"code,optional"`
	Phonenumber  string `json:"phonenumber,optional"`
	Email        string `json:"email,optional"`
	WxCode       string `json:"wxCode,optional"`
	Uuid         string `json:"uuid,optional"`
}

type MenuReq struct {
	Id        int64  `json:"id,optional"`
	MenuName  string `json:"menuName,optional"`
	ParentId  int64  `json:"parentId,optional"`
	Sort      int64  `json:"sort,optional"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Query     string `json:"query,optional"`
	IsFrame   int64  `json:"isFrame,optional"`
	IsCache   int64  `json:"isCache,optional"`
	MenuType  int64  `json:"menuType,optional"`
	Visible   int64  `json:"visible,optional"`
	Status    int64  `json:"status,optional"`
	Perms     string `json:"perms,optional"`
	Icon      string `json:"icon,optional"`
	Remark    string `json:"remark,optional"`
}

type MenuUpdateReq struct {
	Id        int64  `path:"id"`
	MenuName  string `json:"menuName,optional"`
	ParentId  int64  `json:"parentId,optional"`
	Sort      int64  `json:"sort,optional"`
	Path      string `json:"path,optional"`
	Component string `json:"component,optional"`
	Query     string `json:"query,optional"`
	IsFrame   int64  `json:"isFrame,optional"`
	IsCache   int64  `json:"isCache,optional"`
	MenuType  int64  `json:"menuType,optional"`
	Visible   int64  `json:"visible,optional"`
	Status    int64  `json:"status,optional"`
	Perms     string `json:"perms,optional"`
	Icon      string `json:"icon,optional"`
	Remark    string `json:"remark,optional"`
}

type OperLogPageReq struct {
	PageNum      int64  `json:"pageNum,optional"`
	PageSize     int64  `json:"pageSize,optional"`
	Title        string `json:"title,optional"`
	OperName     string `json:"operName,optional"`
	BusinessType string `json:"businessType,optional"`
	Status       string `json:"status,optional"`
	StartTime    string `json:"startTime,optional"`
	EndTime      string `json:"endTime,optional"`
}

type OperLogReq struct {
	Title         string `json:"title"`
	BusinessType  string `json:"businessType,optional"`
	Method        string `json:"method,optional"`
	RequestMethod string `json:"requestMethod,optional"`
	DeviceType    string `json:"deviceType,optional"`
	OperName      string `json:"operName,optional"`
	OperUrl       string `json:"operUrl,optional"`
	OperIp        string `json:"operIp,optional"`
	OperLocation  string `json:"operLocation,optional"`
	OperParam     string `json:"operParam,optional"`
	JsonResult    string `json:"jsonResult,optional"`
	Status        string `json:"status,optional"`
	ErrorMsg      string `json:"errorMsg,optional"`
	CostTime      int64  `json:"costTime,optional"`
	UserAgent     string `json:"userAgent,optional"`
}

type OperLogUpdateReq struct {
	Id            int64  `path:"id"`
	Title         string `json:"title,optional"`
	BusinessType  string `json:"businessType,optional"`
	Method        string `json:"method,optional"`
	RequestMethod string `json:"requestMethod,optional"`
	DeviceType    string `json:"deviceType,optional"`
	OperName      string `json:"operName,optional"`
	OperUrl       string `json:"operUrl,optional"`
	OperIp        string `json:"operIp,optional"`
	OperLocation  string `json:"operLocation,optional"`
	OperParam     string `json:"operParam,optional"`
	JsonResult    string `json:"jsonResult,optional"`
	Status        string `json:"status,optional"`
	ErrorMsg      string `json:"errorMsg,optional"`
	CostTime      int64  `json:"costTime,optional"`
	UserAgent     string `json:"userAgent,optional"`
}

type OrgCreateReq struct {
	ParentId int64  `json:"parentId,optional"`
	OrgName  string `json:"orgName"`
	OrgCode  string `json:"orgCode"`
	OrgType  string `json:"orgType,optional"`
	Leader   string `json:"leader,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Status   int64  `json:"status,optional"`
	Sort     int64  `json:"sort,optional"`
	Remark   string `json:"remark,optional"`
}

type OrgPageReq struct {
	PageNum  int64  `json:"pageNum,optional"`
	PageSize int64  `json:"pageSize,optional"`
	OrgName  string `json:"orgName,optional"`
	OrgCode  string `json:"orgCode,optional"`
	Status   int64  `json:"status,optional"`
	ParentId int64  `json:"parentId,optional"`
}

type OrgUpdateReq struct {
	Id       int64  `path:"id"`
	ParentId int64  `json:"parentId,optional"`
	OrgName  string `json:"orgName,optional"`
	OrgCode  string `json:"orgCode,optional"`
	OrgType  string `json:"orgType,optional"`
	Leader   string `json:"leader,optional"`
	Phone    string `json:"phone,optional"`
	Email    string `json:"email,optional"`
	Status   int64  `json:"status,optional"`
	Sort     int64  `json:"sort,optional"`
	Remark   string `json:"remark,optional"`
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken"`
	ClientKey    string `json:"clientKey"`
	ClientSecret string `json:"clientSecret"`
}

type RemoveRoleReq struct {
	UserId int64 `form:"userId"`
	RoleId int64 `form:"roleId"`
}

type RoleApiPermissionsAssignReq struct {
	RoleId        int64   `path:"roleId"`
	PermissionIds []int64 `json:"permissionIds"`
}

type RoleApiPermissionsPathReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleCreateReq struct {
	RoleKey   string `json:"roleKey"`
	RoleName  string `json:"roleName"`
	Sort      int64  `json:"sort,optional"`
	Status    int64  `json:"status,optional"`
	DataScope int64  `json:"dataScope,optional"`
	Remark    string `json:"remark,optional"`
}

type RoleIdPathReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleMenusAssignReq struct {
	RoleId  int64   `path:"roleId"`
	MenuIds []int64 `json:"menuIds"`
}

type RoleMenusPathReq struct {
	RoleId int64 `path:"roleId"`
}

type RolePageReq struct {
	PageNum  int64  `json:"pageNum,optional"`
	PageSize int64  `json:"pageSize,optional"`
	RoleName string `json:"roleName,optional"`
	Status   int64  `json:"status,optional"`
}

type RolePermissionDeleteReq struct {
	RoleKey  string `form:"roleKey"`
	Resource string `form:"resource"`
	Action   string `form:"action"`
}

type RolePermissionReq struct {
	RoleKey  string `json:"roleKey"`
	Resource string `json:"resource"`
	Action   string `json:"action"`
}

type RolePermissionsQueryReq struct {
	RoleKey string `form:"roleKey"`
}

type RoleUpdateReq struct {
	RoleId    int64  `path:"roleId"`
	RoleName  string `json:"roleName"`
	Sort      int64  `json:"sort,optional"`
	Status    int64  `json:"status,optional"`
	DataScope int64  `json:"dataScope,optional"`
	Remark    string `json:"remark,optional"`
}

type RoleUsersPathReq struct {
	RoleId int64 `path:"roleId"`
}

type RoleUsersReq struct {
	RoleId  int64   `path:"roleId"`
	UserIds []int64 `json:"userIds"`
}

type StorageEnvCreateReq struct {
	Name        string      `json:"name"`
	Code        string      `json:"code"`
	StorageType string      `json:"storageType"`
	IsDefault   bool        `json:"isDefault,optional"`
	Status      int64       `json:"status,optional"`
	Config      interface{} `json:"config,optional"`
	Remark      string      `json:"remark,optional"`
}

type StorageEnvDefaultReq struct {
	Id int64 `json:"id"`
}

type StorageEnvPageReq struct {
	PageNum     int64  `json:"pageNum,optional"`
	PageSize    int64  `json:"pageSize,optional"`
	Name        string `json:"name,optional"`
	StorageType string `json:"storageType,optional"`
}

type StorageEnvTestReq struct {
	Id int64 `path:"id"`
}

type StorageEnvUpdateReq struct {
	Id          int64       `path:"id"`
	Name        string      `json:"name"`
	Code        string      `json:"code"`
	StorageType string      `json:"storageType"`
	IsDefault   bool        `json:"isDefault,optional"`
	Status      int64       `json:"status,optional"`
	Config      interface{} `json:"config"`
	Remark      string      `json:"remark,optional"`
}

type StringIdPathReq struct {
	Id string `path:"id"`
}

type UserApiPermissionsAssignReq struct {
	Id            int64   `path:"id"`
	PermissionIds []int64 `json:"permissionIds"`
}

type UserApiPermissionsPathReq struct {
	Id int64 `path:"id"`
}

type UserChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type UserCreateReq struct {
	UserName    string `json:"userName"`
	NickName    string `json:"nickName"`
	Password    string `json:"password"`
	UserType    int64  `json:"userType,optional"`
	Email       string `json:"email,optional"`
	Phonenumber string `json:"phonenumber,optional"`
	Sex         int64  `json:"sex,optional"`
	Avatar      string `json:"avatar,optional"`
	Status      int64  `json:"status,optional"`
	Remark      string `json:"remark,optional"`
}

type UserImportReq struct {
	Users []UserCreateReq `json:"users"`
}

type UserPageReq struct {
	PageNum     int64  `json:"pageNum,optional"`
	PageSize    int64  `json:"pageSize,optional"`
	Username    string `json:"username,optional"`
	Phonenumber string `json:"phonenumber,optional"`
	Status      int64  `json:"status,optional"`
}

type UserPasswordPathReq struct {
	Id          int64  `path:"id"`
	NewPassword string `json:"newPassword"`
}

type UserRoleQueryReq struct {
	UserId int64 `form:"userId"`
}

type UserUpdateReq struct {
	Id          int64  `path:"id"`
	UserName    string `json:"userName,optional"`
	NickName    string `json:"nickName,optional"`
	UserType    int64  `json:"userType,optional"`
	Email       string `json:"email,optional"`
	Phonenumber string `json:"phonenumber,optional"`
	Sex         int64  `json:"sex,optional"`
	Avatar      string `json:"avatar,optional"`
	Status      int64  `json:"status,optional"`
	Remark      string `json:"remark,optional"`
}
