// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sUserFieldNames          = builder.RawFieldNames(&SUser{}, true)
	sUserRows                = strings.Join(sUserFieldNames, ",")
	sUserRowsExpectAutoSet   = strings.Join(stringx.Remove(sUserFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	sUserRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(sUserFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	sUserModel interface {
		Insert(ctx context.Context, data *SUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SUser, error)
		FindOneByUserName(ctx context.Context, userName string) (*SUser, error)
		Update(ctx context.Context, data *SUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SUser struct {
		Id          int64          `db:"id"`
		UserName    string         `db:"user_name"`
		NickName    sql.NullString `db:"nick_name"`
		UserType    int64          `db:"user_type"`
		Email       sql.NullString `db:"email"`
		Phonenumber sql.NullString `db:"phonenumber"`
		Sex         int64          `db:"sex"`
		Avatar      sql.NullString `db:"avatar"`
		Password    sql.NullString `db:"password"`
		Status      int64          `db:"status"`
		Sort        int64          `db:"sort"`
		LoginIp     sql.NullString `db:"login_ip"`
		LoginDate   sql.NullInt64  `db:"login_date"`
		OpenId      sql.NullString `db:"open_id"`
		UnionId     sql.NullString `db:"union_id"`
		Remark      sql.NullString `db:"remark"`
		CreateBy    sql.NullInt64  `db:"create_by"`
		UpdateBy    sql.NullInt64  `db:"update_by"`
		CreatedTime sql.NullTime   `db:"created_time"`
		UpdatedTime sql.NullTime   `db:"updated_time"`
		OrgId       int64          `db:"org_id"`
	}
)

func newSUserModel(conn sqlx.SqlConn) *defaultSUserModel {
	return &defaultSUserModel{
		conn:  conn,
		table: `"public"."s_user"`,
	}
}

func (m *defaultSUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSUserModel) FindOne(ctx context.Context, id int64) (*SUser, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", sUserRows, m.table)
	var resp SUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSUserModel) FindOneByUserName(ctx context.Context, userName string) (*SUser, error) {
	var resp SUser
	query := fmt.Sprintf("select %s from %s where user_name = $1 limit 1", sUserRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, userName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSUserModel) Insert(ctx context.Context, data *SUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, $19, $20)", m.table, sUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserName, data.NickName, data.UserType, data.Email, data.Phonenumber, data.Sex, data.Avatar, data.Password, data.Status, data.Sort, data.LoginIp, data.LoginDate, data.OpenId, data.UnionId, data.Remark, data.CreateBy, data.UpdateBy, data.CreatedTime, data.UpdatedTime, data.OrgId)
	return ret, err
}

func (m *defaultSUserModel) Update(ctx context.Context, newData *SUser) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, sUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UserName, newData.NickName, newData.UserType, newData.Email, newData.Phonenumber, newData.Sex, newData.Avatar, newData.Password, newData.Status, newData.Sort, newData.LoginIp, newData.LoginDate, newData.OpenId, newData.UnionId, newData.Remark, newData.CreateBy, newData.UpdateBy, newData.CreatedTime, newData.UpdatedTime, newData.OrgId)
	return err
}

func (m *defaultSUserModel) tableName() string {
	return m.table
}
