// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	attachment "github.com/force-c/nai-tizi/application/sys-api/internal/handler/attachment"
	auth "github.com/force-c/nai-tizi/application/sys-api/internal/handler/auth"
	captcha "github.com/force-c/nai-tizi/application/sys-api/internal/handler/captcha"
	config "github.com/force-c/nai-tizi/application/sys-api/internal/handler/config"
	dict "github.com/force-c/nai-tizi/application/sys-api/internal/handler/dict"
	health "github.com/force-c/nai-tizi/application/sys-api/internal/handler/health"
	loginlog "github.com/force-c/nai-tizi/application/sys-api/internal/handler/loginlog"
	menu "github.com/force-c/nai-tizi/application/sys-api/internal/handler/menu"
	operlog "github.com/force-c/nai-tizi/application/sys-api/internal/handler/operlog"
	org "github.com/force-c/nai-tizi/application/sys-api/internal/handler/org"
	role "github.com/force-c/nai-tizi/application/sys-api/internal/handler/role"
	storageenv "github.com/force-c/nai-tizi/application/sys-api/internal/handler/storageenv"
	user "github.com/force-c/nai-tizi/application/sys-api/internal/handler/user"
	"github.com/force-c/nai-tizi/application/sys-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/attachment/:attachmentId",
				Handler: attachment.AttachmentDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/attachment/:attachmentId",
				Handler: attachment.AttachmentDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/attachment/:attachmentId/bind",
				Handler: attachment.AttachmentBindHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/attachment/:attachmentId/download",
				Handler: attachment.AttachmentDownloadHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/attachment/:attachmentId/url",
				Handler: attachment.AttachmentUrlHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/attachment/business",
				Handler: attachment.AttachmentBusinessHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/attachment/page",
				Handler: attachment.AttachmentPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/attachment/upload-file",
				Handler: attachment.AttachmentUploadFileHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/auth/refresh",
				Handler: auth.RefreshTokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/captcha/email",
				Handler: captcha.CaptchaEmailHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/captcha/enabled-types",
				Handler: captcha.CaptchaEnabledTypesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/captcha/image",
				Handler: captcha.CaptchaImageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/captcha/sms",
				Handler: captcha.CaptchaSmsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/config",
				Handler: config.ConfigCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/config/:id",
				Handler: config.ConfigUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/:id",
				Handler: config.ConfigDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/config/:id",
				Handler: config.ConfigDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/config/batch",
				Handler: config.ConfigBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/code",
				Handler: config.ConfigCodeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/data",
				Handler: config.ConfigDataHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/config/page",
				Handler: config.ConfigPageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/dict",
				Handler: dict.DictCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/dict/:id",
				Handler: dict.DictUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/dict/:id",
				Handler: dict.DictDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/dict/:id",
				Handler: dict.DictDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/dict/batch",
				Handler: dict.DictBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/dict/label",
				Handler: dict.DictLabelHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/dict/page",
				Handler: dict.DictPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/dict/type",
				Handler: dict.DictTypeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: health.HealthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/live",
				Handler: health.HealthLiveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/ready",
				Handler: health.HealthReadyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/health/startup",
				Handler: health.HealthStartupHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/loginLog",
				Handler: loginlog.LoginLogCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/loginLog/:id",
				Handler: loginlog.LoginLogUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/loginLog/:id",
				Handler: loginlog.LoginLogDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/loginLog/:id",
				Handler: loginlog.LoginLogDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/loginLog/batch",
				Handler: loginlog.LoginLogBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/loginLog/clean",
				Handler: loginlog.LoginLogCleanHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/loginLog/page",
				Handler: loginlog.LoginLogPageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/menu",
				Handler: menu.MenuListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/menu",
				Handler: menu.MenuCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/menu/:id",
				Handler: menu.MenuDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/menu/:id",
				Handler: menu.MenuUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/menu/:id",
				Handler: menu.MenuDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/menu/tree",
				Handler: menu.MenuTreeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/menu/user/tree",
				Handler: menu.MenuUserTreeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/operLog",
				Handler: operlog.OperLogCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/operLog/:id",
				Handler: operlog.OperLogUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/operLog/:id",
				Handler: operlog.OperLogDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/operLog/:id",
				Handler: operlog.OperLogDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/operLog/batch",
				Handler: operlog.OperLogBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/operLog/clean",
				Handler: operlog.OperLogCleanHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/operLog/page",
				Handler: operlog.OperLogPageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/org",
				Handler: org.OrgCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/org/:id",
				Handler: org.OrgUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/org/:id",
				Handler: org.OrgDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/org/:id",
				Handler: org.OrgDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/org/batch",
				Handler: org.OrgBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/org/page",
				Handler: org.OrgPageHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/org/tree",
				Handler: org.OrgTreeHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/role",
				Handler: role.RoleCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/role/:roleId",
				Handler: role.RoleUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/role/:roleId",
				Handler: role.RoleDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/role/:roleId",
				Handler: role.RoleDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/role/:roleId/menus",
				Handler: role.RoleMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/role/:roleId/menus",
				Handler: role.RoleAssignMenusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/role/assign",
				Handler: role.RoleAssignHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/role/page",
				Handler: role.RolePageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/role/permission",
				Handler: role.RolePermissionAddHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/role/permission",
				Handler: role.RolePermissionDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/role/permissions",
				Handler: role.RolePermissionsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/role/remove",
				Handler: role.RoleRemoveHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/role/user",
				Handler: role.RoleUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/storage-env",
				Handler: storageenv.StorageEnvCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/storage-env/:id",
				Handler: storageenv.StorageEnvUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/storage-env/:id",
				Handler: storageenv.StorageEnvDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/storage-env/:id",
				Handler: storageenv.StorageEnvDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/storage-env/:id/test",
				Handler: storageenv.StorageEnvTestHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/storage-env/default",
				Handler: storageenv.StorageEnvDefaultHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/storage-env/default",
				Handler: storageenv.StorageEnvSetDefaultHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/storage-env/page",
				Handler: storageenv.StorageEnvPageHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/user",
				Handler: user.UserCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/user/:id",
				Handler: user.UserUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/user/:id",
				Handler: user.UserDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/user/:id",
				Handler: user.UserDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/user/:id/password",
				Handler: user.UserResetPasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/user/batch",
				Handler: user.UserBatchDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/user/import",
				Handler: user.UserImportHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/user/page",
				Handler: user.UserPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/user/password/change",
				Handler: user.UserChangePasswordHandler(serverCtx),
			},
		},
	)
}
