// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/authclient"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/predicate"
)

// AuthClientUpdate is the builder for updating AuthClient entities.
type AuthClientUpdate struct {
	config
	hooks    []Hook
	mutation *AuthClientMutation
}

// Where appends a list predicates to the AuthClientUpdate builder.
func (_u *AuthClientUpdate) Where(ps ...predicate.AuthClient) *AuthClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *AuthClientUpdate) SetCreateBy(v int64) *AuthClientUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableCreateBy(v *int64) *AuthClientUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *AuthClientUpdate) AddCreateBy(v int64) *AuthClientUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *AuthClientUpdate) SetUpdateBy(v int64) *AuthClientUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableUpdateBy(v *int64) *AuthClientUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *AuthClientUpdate) AddUpdateBy(v int64) *AuthClientUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// SetCreatedTime sets the "created_time" field.
func (_u *AuthClientUpdate) SetCreatedTime(v time.Time) *AuthClientUpdate {
	_u.mutation.SetCreatedTime(v)
	return _u
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableCreatedTime(v *time.Time) *AuthClientUpdate {
	if v != nil {
		_u.SetCreatedTime(*v)
	}
	return _u
}

// SetUpdatedTime sets the "updated_time" field.
func (_u *AuthClientUpdate) SetUpdatedTime(v time.Time) *AuthClientUpdate {
	_u.mutation.SetUpdatedTime(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthClientUpdate) SetDeletedAt(v time.Time) *AuthClientUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableDeletedAt(v *time.Time) *AuthClientUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AuthClientUpdate) ClearDeletedAt() *AuthClientUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AuthClientUpdate) SetClientID(v string) *AuthClientUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableClientID(v *string) *AuthClientUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientKey sets the "client_key" field.
func (_u *AuthClientUpdate) SetClientKey(v string) *AuthClientUpdate {
	_u.mutation.SetClientKey(v)
	return _u
}

// SetNillableClientKey sets the "client_key" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableClientKey(v *string) *AuthClientUpdate {
	if v != nil {
		_u.SetClientKey(*v)
	}
	return _u
}

// SetClientSecret sets the "client_secret" field.
func (_u *AuthClientUpdate) SetClientSecret(v string) *AuthClientUpdate {
	_u.mutation.SetClientSecret(v)
	return _u
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableClientSecret(v *string) *AuthClientUpdate {
	if v != nil {
		_u.SetClientSecret(*v)
	}
	return _u
}

// SetGrantType sets the "grant_type" field.
func (_u *AuthClientUpdate) SetGrantType(v string) *AuthClientUpdate {
	_u.mutation.SetGrantType(v)
	return _u
}

// SetNillableGrantType sets the "grant_type" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableGrantType(v *string) *AuthClientUpdate {
	if v != nil {
		_u.SetGrantType(*v)
	}
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *AuthClientUpdate) SetDeviceType(v string) *AuthClientUpdate {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableDeviceType(v *string) *AuthClientUpdate {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AuthClientUpdate) SetStatus(v int32) *AuthClientUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableStatus(v *int32) *AuthClientUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AuthClientUpdate) AddStatus(v int32) *AuthClientUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetTimeout sets the "timeout" field.
func (_u *AuthClientUpdate) SetTimeout(v int64) *AuthClientUpdate {
	_u.mutation.ResetTimeout()
	_u.mutation.SetTimeout(v)
	return _u
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableTimeout(v *int64) *AuthClientUpdate {
	if v != nil {
		_u.SetTimeout(*v)
	}
	return _u
}

// AddTimeout adds value to the "timeout" field.
func (_u *AuthClientUpdate) AddTimeout(v int64) *AuthClientUpdate {
	_u.mutation.AddTimeout(v)
	return _u
}

// SetActiveTimeout sets the "active_timeout" field.
func (_u *AuthClientUpdate) SetActiveTimeout(v int64) *AuthClientUpdate {
	_u.mutation.ResetActiveTimeout()
	_u.mutation.SetActiveTimeout(v)
	return _u
}

// SetNillableActiveTimeout sets the "active_timeout" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableActiveTimeout(v *int64) *AuthClientUpdate {
	if v != nil {
		_u.SetActiveTimeout(*v)
	}
	return _u
}

// AddActiveTimeout adds value to the "active_timeout" field.
func (_u *AuthClientUpdate) AddActiveTimeout(v int64) *AuthClientUpdate {
	_u.mutation.AddActiveTimeout(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *AuthClientUpdate) SetRemark(v string) *AuthClientUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *AuthClientUpdate) SetNillableRemark(v *string) *AuthClientUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// Mutation returns the AuthClientMutation object of the builder.
func (_u *AuthClientUpdate) Mutation() *AuthClientMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthClientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthClientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedTime(); !ok {
		v := authclient.UpdateDefaultUpdatedTime()
		_u.mutation.SetUpdatedTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthClientUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := authclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AuthClient.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientKey(); ok {
		if err := authclient.ClientKeyValidator(v); err != nil {
			return &ValidationError{Name: "client_key", err: fmt.Errorf(`ent: validator failed for field "AuthClient.client_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientSecret(); ok {
		if err := authclient.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "AuthClient.client_secret": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authclient.Table, authclient.Columns, sqlgraph.NewFieldSpec(authclient.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(authclient.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(authclient.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(authclient.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(authclient.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedTime(); ok {
		_spec.SetField(authclient.FieldCreatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedTime(); ok {
		_spec.SetField(authclient.FieldUpdatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authclient.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(authclient.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(authclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientKey(); ok {
		_spec.SetField(authclient.FieldClientKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecret(); ok {
		_spec.SetField(authclient.FieldClientSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantType(); ok {
		_spec.SetField(authclient.FieldGrantType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(authclient.FieldDeviceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(authclient.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(authclient.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Timeout(); ok {
		_spec.SetField(authclient.FieldTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeout(); ok {
		_spec.AddField(authclient.FieldTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActiveTimeout(); ok {
		_spec.SetField(authclient.FieldActiveTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveTimeout(); ok {
		_spec.AddField(authclient.FieldActiveTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(authclient.FieldRemark, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthClientUpdateOne is the builder for updating a single AuthClient entity.
type AuthClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthClientMutation
}

// SetCreateBy sets the "create_by" field.
func (_u *AuthClientUpdateOne) SetCreateBy(v int64) *AuthClientUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableCreateBy(v *int64) *AuthClientUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *AuthClientUpdateOne) AddCreateBy(v int64) *AuthClientUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *AuthClientUpdateOne) SetUpdateBy(v int64) *AuthClientUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableUpdateBy(v *int64) *AuthClientUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *AuthClientUpdateOne) AddUpdateBy(v int64) *AuthClientUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// SetCreatedTime sets the "created_time" field.
func (_u *AuthClientUpdateOne) SetCreatedTime(v time.Time) *AuthClientUpdateOne {
	_u.mutation.SetCreatedTime(v)
	return _u
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableCreatedTime(v *time.Time) *AuthClientUpdateOne {
	if v != nil {
		_u.SetCreatedTime(*v)
	}
	return _u
}

// SetUpdatedTime sets the "updated_time" field.
func (_u *AuthClientUpdateOne) SetUpdatedTime(v time.Time) *AuthClientUpdateOne {
	_u.mutation.SetUpdatedTime(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AuthClientUpdateOne) SetDeletedAt(v time.Time) *AuthClientUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableDeletedAt(v *time.Time) *AuthClientUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AuthClientUpdateOne) ClearDeletedAt() *AuthClientUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AuthClientUpdateOne) SetClientID(v string) *AuthClientUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableClientID(v *string) *AuthClientUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetClientKey sets the "client_key" field.
func (_u *AuthClientUpdateOne) SetClientKey(v string) *AuthClientUpdateOne {
	_u.mutation.SetClientKey(v)
	return _u
}

// SetNillableClientKey sets the "client_key" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableClientKey(v *string) *AuthClientUpdateOne {
	if v != nil {
		_u.SetClientKey(*v)
	}
	return _u
}

// SetClientSecret sets the "client_secret" field.
func (_u *AuthClientUpdateOne) SetClientSecret(v string) *AuthClientUpdateOne {
	_u.mutation.SetClientSecret(v)
	return _u
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableClientSecret(v *string) *AuthClientUpdateOne {
	if v != nil {
		_u.SetClientSecret(*v)
	}
	return _u
}

// SetGrantType sets the "grant_type" field.
func (_u *AuthClientUpdateOne) SetGrantType(v string) *AuthClientUpdateOne {
	_u.mutation.SetGrantType(v)
	return _u
}

// SetNillableGrantType sets the "grant_type" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableGrantType(v *string) *AuthClientUpdateOne {
	if v != nil {
		_u.SetGrantType(*v)
	}
	return _u
}

// SetDeviceType sets the "device_type" field.
func (_u *AuthClientUpdateOne) SetDeviceType(v string) *AuthClientUpdateOne {
	_u.mutation.SetDeviceType(v)
	return _u
}

// SetNillableDeviceType sets the "device_type" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableDeviceType(v *string) *AuthClientUpdateOne {
	if v != nil {
		_u.SetDeviceType(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AuthClientUpdateOne) SetStatus(v int32) *AuthClientUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableStatus(v *int32) *AuthClientUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AuthClientUpdateOne) AddStatus(v int32) *AuthClientUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetTimeout sets the "timeout" field.
func (_u *AuthClientUpdateOne) SetTimeout(v int64) *AuthClientUpdateOne {
	_u.mutation.ResetTimeout()
	_u.mutation.SetTimeout(v)
	return _u
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableTimeout(v *int64) *AuthClientUpdateOne {
	if v != nil {
		_u.SetTimeout(*v)
	}
	return _u
}

// AddTimeout adds value to the "timeout" field.
func (_u *AuthClientUpdateOne) AddTimeout(v int64) *AuthClientUpdateOne {
	_u.mutation.AddTimeout(v)
	return _u
}

// SetActiveTimeout sets the "active_timeout" field.
func (_u *AuthClientUpdateOne) SetActiveTimeout(v int64) *AuthClientUpdateOne {
	_u.mutation.ResetActiveTimeout()
	_u.mutation.SetActiveTimeout(v)
	return _u
}

// SetNillableActiveTimeout sets the "active_timeout" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableActiveTimeout(v *int64) *AuthClientUpdateOne {
	if v != nil {
		_u.SetActiveTimeout(*v)
	}
	return _u
}

// AddActiveTimeout adds value to the "active_timeout" field.
func (_u *AuthClientUpdateOne) AddActiveTimeout(v int64) *AuthClientUpdateOne {
	_u.mutation.AddActiveTimeout(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *AuthClientUpdateOne) SetRemark(v string) *AuthClientUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *AuthClientUpdateOne) SetNillableRemark(v *string) *AuthClientUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// Mutation returns the AuthClientMutation object of the builder.
func (_u *AuthClientUpdateOne) Mutation() *AuthClientMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthClientUpdate builder.
func (_u *AuthClientUpdateOne) Where(ps ...predicate.AuthClient) *AuthClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthClientUpdateOne) Select(field string, fields ...string) *AuthClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthClient entity.
func (_u *AuthClientUpdateOne) Save(ctx context.Context) (*AuthClient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthClientUpdateOne) SaveX(ctx context.Context) *AuthClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthClientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedTime(); !ok {
		v := authclient.UpdateDefaultUpdatedTime()
		_u.mutation.SetUpdatedTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthClientUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := authclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "AuthClient.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientKey(); ok {
		if err := authclient.ClientKeyValidator(v); err != nil {
			return &ValidationError{Name: "client_key", err: fmt.Errorf(`ent: validator failed for field "AuthClient.client_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientSecret(); ok {
		if err := authclient.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "AuthClient.client_secret": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthClientUpdateOne) sqlSave(ctx context.Context) (_node *AuthClient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authclient.Table, authclient.Columns, sqlgraph.NewFieldSpec(authclient.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authclient.FieldID)
		for _, f := range fields {
			if !authclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(authclient.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(authclient.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(authclient.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(authclient.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedTime(); ok {
		_spec.SetField(authclient.FieldCreatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedTime(); ok {
		_spec.SetField(authclient.FieldUpdatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(authclient.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(authclient.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(authclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientKey(); ok {
		_spec.SetField(authclient.FieldClientKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientSecret(); ok {
		_spec.SetField(authclient.FieldClientSecret, field.TypeString, value)
	}
	if value, ok := _u.mutation.GrantType(); ok {
		_spec.SetField(authclient.FieldGrantType, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeviceType(); ok {
		_spec.SetField(authclient.FieldDeviceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(authclient.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(authclient.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Timeout(); ok {
		_spec.SetField(authclient.FieldTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTimeout(); ok {
		_spec.AddField(authclient.FieldTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ActiveTimeout(); ok {
		_spec.SetField(authclient.FieldActiveTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActiveTimeout(); ok {
		_spec.AddField(authclient.FieldActiveTimeout, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(authclient.FieldRemark, field.TypeString, value)
	}
	_node = &AuthClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
