// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/dictdata"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/predicate"
)

// DictDataUpdate is the builder for updating DictData entities.
type DictDataUpdate struct {
	config
	hooks    []Hook
	mutation *DictDataMutation
}

// Where appends a list predicates to the DictDataUpdate builder.
func (_u *DictDataUpdate) Where(ps ...predicate.DictData) *DictDataUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *DictDataUpdate) SetCreateBy(v int64) *DictDataUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableCreateBy(v *int64) *DictDataUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *DictDataUpdate) AddCreateBy(v int64) *DictDataUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *DictDataUpdate) SetUpdateBy(v int64) *DictDataUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableUpdateBy(v *int64) *DictDataUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *DictDataUpdate) AddUpdateBy(v int64) *DictDataUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// SetCreatedTime sets the "created_time" field.
func (_u *DictDataUpdate) SetCreatedTime(v time.Time) *DictDataUpdate {
	_u.mutation.SetCreatedTime(v)
	return _u
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableCreatedTime(v *time.Time) *DictDataUpdate {
	if v != nil {
		_u.SetCreatedTime(*v)
	}
	return _u
}

// SetUpdatedTime sets the "updated_time" field.
func (_u *DictDataUpdate) SetUpdatedTime(v time.Time) *DictDataUpdate {
	_u.mutation.SetUpdatedTime(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictDataUpdate) SetDeletedAt(v time.Time) *DictDataUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableDeletedAt(v *time.Time) *DictDataUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictDataUpdate) ClearDeletedAt() *DictDataUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DictDataUpdate) SetParentID(v int64) *DictDataUpdate {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableParentID(v *int64) *DictDataUpdate {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *DictDataUpdate) AddParentID(v int64) *DictDataUpdate {
	_u.mutation.AddParentID(v)
	return _u
}

// SetSort sets the "sort" field.
func (_u *DictDataUpdate) SetSort(v int64) *DictDataUpdate {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableSort(v *int64) *DictDataUpdate {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *DictDataUpdate) AddSort(v int64) *DictDataUpdate {
	_u.mutation.AddSort(v)
	return _u
}

// SetDictLabel sets the "dict_label" field.
func (_u *DictDataUpdate) SetDictLabel(v string) *DictDataUpdate {
	_u.mutation.SetDictLabel(v)
	return _u
}

// SetNillableDictLabel sets the "dict_label" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableDictLabel(v *string) *DictDataUpdate {
	if v != nil {
		_u.SetDictLabel(*v)
	}
	return _u
}

// SetDictValue sets the "dict_value" field.
func (_u *DictDataUpdate) SetDictValue(v string) *DictDataUpdate {
	_u.mutation.SetDictValue(v)
	return _u
}

// SetNillableDictValue sets the "dict_value" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableDictValue(v *string) *DictDataUpdate {
	if v != nil {
		_u.SetDictValue(*v)
	}
	return _u
}

// SetDictType sets the "dict_type" field.
func (_u *DictDataUpdate) SetDictType(v string) *DictDataUpdate {
	_u.mutation.SetDictType(v)
	return _u
}

// SetNillableDictType sets the "dict_type" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableDictType(v *string) *DictDataUpdate {
	if v != nil {
		_u.SetDictType(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *DictDataUpdate) SetIsDefault(v bool) *DictDataUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableIsDefault(v *bool) *DictDataUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DictDataUpdate) SetStatus(v int32) *DictDataUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableStatus(v *int32) *DictDataUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DictDataUpdate) AddStatus(v int32) *DictDataUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DictDataUpdate) SetRemark(v string) *DictDataUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DictDataUpdate) SetNillableRemark(v *string) *DictDataUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// Mutation returns the DictDataMutation object of the builder.
func (_u *DictDataUpdate) Mutation() *DictDataMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DictDataUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictDataUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DictDataUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictDataUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictDataUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedTime(); !ok {
		v := dictdata.UpdateDefaultUpdatedTime()
		_u.mutation.SetUpdatedTime(v)
	}
}

func (_u *DictDataUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dictdata.Table, dictdata.Columns, sqlgraph.NewFieldSpec(dictdata.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(dictdata.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(dictdata.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(dictdata.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(dictdata.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedTime(); ok {
		_spec.SetField(dictdata.FieldCreatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedTime(); ok {
		_spec.SetField(dictdata.FieldUpdatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictdata.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictdata.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(dictdata.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(dictdata.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(dictdata.FieldSort, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(dictdata.FieldSort, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DictLabel(); ok {
		_spec.SetField(dictdata.FieldDictLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DictValue(); ok {
		_spec.SetField(dictdata.FieldDictValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.DictType(); ok {
		_spec.SetField(dictdata.FieldDictType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(dictdata.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dictdata.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(dictdata.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(dictdata.FieldRemark, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictdata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DictDataUpdateOne is the builder for updating a single DictData entity.
type DictDataUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DictDataMutation
}

// SetCreateBy sets the "create_by" field.
func (_u *DictDataUpdateOne) SetCreateBy(v int64) *DictDataUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableCreateBy(v *int64) *DictDataUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *DictDataUpdateOne) AddCreateBy(v int64) *DictDataUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *DictDataUpdateOne) SetUpdateBy(v int64) *DictDataUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableUpdateBy(v *int64) *DictDataUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *DictDataUpdateOne) AddUpdateBy(v int64) *DictDataUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// SetCreatedTime sets the "created_time" field.
func (_u *DictDataUpdateOne) SetCreatedTime(v time.Time) *DictDataUpdateOne {
	_u.mutation.SetCreatedTime(v)
	return _u
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableCreatedTime(v *time.Time) *DictDataUpdateOne {
	if v != nil {
		_u.SetCreatedTime(*v)
	}
	return _u
}

// SetUpdatedTime sets the "updated_time" field.
func (_u *DictDataUpdateOne) SetUpdatedTime(v time.Time) *DictDataUpdateOne {
	_u.mutation.SetUpdatedTime(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *DictDataUpdateOne) SetDeletedAt(v time.Time) *DictDataUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableDeletedAt(v *time.Time) *DictDataUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *DictDataUpdateOne) ClearDeletedAt() *DictDataUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetParentID sets the "parent_id" field.
func (_u *DictDataUpdateOne) SetParentID(v int64) *DictDataUpdateOne {
	_u.mutation.ResetParentID()
	_u.mutation.SetParentID(v)
	return _u
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableParentID(v *int64) *DictDataUpdateOne {
	if v != nil {
		_u.SetParentID(*v)
	}
	return _u
}

// AddParentID adds value to the "parent_id" field.
func (_u *DictDataUpdateOne) AddParentID(v int64) *DictDataUpdateOne {
	_u.mutation.AddParentID(v)
	return _u
}

// SetSort sets the "sort" field.
func (_u *DictDataUpdateOne) SetSort(v int64) *DictDataUpdateOne {
	_u.mutation.ResetSort()
	_u.mutation.SetSort(v)
	return _u
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableSort(v *int64) *DictDataUpdateOne {
	if v != nil {
		_u.SetSort(*v)
	}
	return _u
}

// AddSort adds value to the "sort" field.
func (_u *DictDataUpdateOne) AddSort(v int64) *DictDataUpdateOne {
	_u.mutation.AddSort(v)
	return _u
}

// SetDictLabel sets the "dict_label" field.
func (_u *DictDataUpdateOne) SetDictLabel(v string) *DictDataUpdateOne {
	_u.mutation.SetDictLabel(v)
	return _u
}

// SetNillableDictLabel sets the "dict_label" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableDictLabel(v *string) *DictDataUpdateOne {
	if v != nil {
		_u.SetDictLabel(*v)
	}
	return _u
}

// SetDictValue sets the "dict_value" field.
func (_u *DictDataUpdateOne) SetDictValue(v string) *DictDataUpdateOne {
	_u.mutation.SetDictValue(v)
	return _u
}

// SetNillableDictValue sets the "dict_value" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableDictValue(v *string) *DictDataUpdateOne {
	if v != nil {
		_u.SetDictValue(*v)
	}
	return _u
}

// SetDictType sets the "dict_type" field.
func (_u *DictDataUpdateOne) SetDictType(v string) *DictDataUpdateOne {
	_u.mutation.SetDictType(v)
	return _u
}

// SetNillableDictType sets the "dict_type" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableDictType(v *string) *DictDataUpdateOne {
	if v != nil {
		_u.SetDictType(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *DictDataUpdateOne) SetIsDefault(v bool) *DictDataUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableIsDefault(v *bool) *DictDataUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DictDataUpdateOne) SetStatus(v int32) *DictDataUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableStatus(v *int32) *DictDataUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *DictDataUpdateOne) AddStatus(v int32) *DictDataUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetRemark sets the "remark" field.
func (_u *DictDataUpdateOne) SetRemark(v string) *DictDataUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *DictDataUpdateOne) SetNillableRemark(v *string) *DictDataUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// Mutation returns the DictDataMutation object of the builder.
func (_u *DictDataUpdateOne) Mutation() *DictDataMutation {
	return _u.mutation
}

// Where appends a list predicates to the DictDataUpdate builder.
func (_u *DictDataUpdateOne) Where(ps ...predicate.DictData) *DictDataUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DictDataUpdateOne) Select(field string, fields ...string) *DictDataUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DictData entity.
func (_u *DictDataUpdateOne) Save(ctx context.Context) (*DictData, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DictDataUpdateOne) SaveX(ctx context.Context) *DictData {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DictDataUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DictDataUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DictDataUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedTime(); !ok {
		v := dictdata.UpdateDefaultUpdatedTime()
		_u.mutation.SetUpdatedTime(v)
	}
}

func (_u *DictDataUpdateOne) sqlSave(ctx context.Context) (_node *DictData, err error) {
	_spec := sqlgraph.NewUpdateSpec(dictdata.Table, dictdata.Columns, sqlgraph.NewFieldSpec(dictdata.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DictData.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dictdata.FieldID)
		for _, f := range fields {
			if !dictdata.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dictdata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(dictdata.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(dictdata.FieldCreateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(dictdata.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(dictdata.FieldUpdateBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatedTime(); ok {
		_spec.SetField(dictdata.FieldCreatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedTime(); ok {
		_spec.SetField(dictdata.FieldUpdatedTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(dictdata.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(dictdata.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ParentID(); ok {
		_spec.SetField(dictdata.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedParentID(); ok {
		_spec.AddField(dictdata.FieldParentID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Sort(); ok {
		_spec.SetField(dictdata.FieldSort, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSort(); ok {
		_spec.AddField(dictdata.FieldSort, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DictLabel(); ok {
		_spec.SetField(dictdata.FieldDictLabel, field.TypeString, value)
	}
	if value, ok := _u.mutation.DictValue(); ok {
		_spec.SetField(dictdata.FieldDictValue, field.TypeString, value)
	}
	if value, ok := _u.mutation.DictType(); ok {
		_spec.SetField(dictdata.FieldDictType, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(dictdata.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(dictdata.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(dictdata.FieldStatus, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(dictdata.FieldRemark, field.TypeString, value)
	}
	_node = &DictData{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dictdata.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
