// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/menu"
)

// MenuCreate is the builder for creating a Menu entity.
type MenuCreate struct {
	config
	mutation *MenuMutation
	hooks    []Hook
}

// SetCreateBy sets the "create_by" field.
func (_c *MenuCreate) SetCreateBy(v int64) *MenuCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *MenuCreate) SetNillableCreateBy(v *int64) *MenuCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *MenuCreate) SetUpdateBy(v int64) *MenuCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *MenuCreate) SetNillableUpdateBy(v *int64) *MenuCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreatedTime sets the "created_time" field.
func (_c *MenuCreate) SetCreatedTime(v time.Time) *MenuCreate {
	_c.mutation.SetCreatedTime(v)
	return _c
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_c *MenuCreate) SetNillableCreatedTime(v *time.Time) *MenuCreate {
	if v != nil {
		_c.SetCreatedTime(*v)
	}
	return _c
}

// SetUpdatedTime sets the "updated_time" field.
func (_c *MenuCreate) SetUpdatedTime(v time.Time) *MenuCreate {
	_c.mutation.SetUpdatedTime(v)
	return _c
}

// SetNillableUpdatedTime sets the "updated_time" field if the given value is not nil.
func (_c *MenuCreate) SetNillableUpdatedTime(v *time.Time) *MenuCreate {
	if v != nil {
		_c.SetUpdatedTime(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *MenuCreate) SetDeletedAt(v time.Time) *MenuCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *MenuCreate) SetNillableDeletedAt(v *time.Time) *MenuCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetMenuName sets the "menu_name" field.
func (_c *MenuCreate) SetMenuName(v string) *MenuCreate {
	_c.mutation.SetMenuName(v)
	return _c
}

// SetParentID sets the "parent_id" field.
func (_c *MenuCreate) SetParentID(v int64) *MenuCreate {
	_c.mutation.SetParentID(v)
	return _c
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (_c *MenuCreate) SetNillableParentID(v *int64) *MenuCreate {
	if v != nil {
		_c.SetParentID(*v)
	}
	return _c
}

// SetSort sets the "sort" field.
func (_c *MenuCreate) SetSort(v int64) *MenuCreate {
	_c.mutation.SetSort(v)
	return _c
}

// SetNillableSort sets the "sort" field if the given value is not nil.
func (_c *MenuCreate) SetNillableSort(v *int64) *MenuCreate {
	if v != nil {
		_c.SetSort(*v)
	}
	return _c
}

// SetPath sets the "path" field.
func (_c *MenuCreate) SetPath(v string) *MenuCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetNillablePath sets the "path" field if the given value is not nil.
func (_c *MenuCreate) SetNillablePath(v *string) *MenuCreate {
	if v != nil {
		_c.SetPath(*v)
	}
	return _c
}

// SetComponent sets the "component" field.
func (_c *MenuCreate) SetComponent(v string) *MenuCreate {
	_c.mutation.SetComponent(v)
	return _c
}

// SetNillableComponent sets the "component" field if the given value is not nil.
func (_c *MenuCreate) SetNillableComponent(v *string) *MenuCreate {
	if v != nil {
		_c.SetComponent(*v)
	}
	return _c
}

// SetQuery sets the "query" field.
func (_c *MenuCreate) SetQuery(v string) *MenuCreate {
	_c.mutation.SetQuery(v)
	return _c
}

// SetNillableQuery sets the "query" field if the given value is not nil.
func (_c *MenuCreate) SetNillableQuery(v *string) *MenuCreate {
	if v != nil {
		_c.SetQuery(*v)
	}
	return _c
}

// SetIsFrame sets the "is_frame" field.
func (_c *MenuCreate) SetIsFrame(v int32) *MenuCreate {
	_c.mutation.SetIsFrame(v)
	return _c
}

// SetNillableIsFrame sets the "is_frame" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIsFrame(v *int32) *MenuCreate {
	if v != nil {
		_c.SetIsFrame(*v)
	}
	return _c
}

// SetIsCache sets the "is_cache" field.
func (_c *MenuCreate) SetIsCache(v int32) *MenuCreate {
	_c.mutation.SetIsCache(v)
	return _c
}

// SetNillableIsCache sets the "is_cache" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIsCache(v *int32) *MenuCreate {
	if v != nil {
		_c.SetIsCache(*v)
	}
	return _c
}

// SetMenuType sets the "menu_type" field.
func (_c *MenuCreate) SetMenuType(v int32) *MenuCreate {
	_c.mutation.SetMenuType(v)
	return _c
}

// SetNillableMenuType sets the "menu_type" field if the given value is not nil.
func (_c *MenuCreate) SetNillableMenuType(v *int32) *MenuCreate {
	if v != nil {
		_c.SetMenuType(*v)
	}
	return _c
}

// SetVisible sets the "visible" field.
func (_c *MenuCreate) SetVisible(v int32) *MenuCreate {
	_c.mutation.SetVisible(v)
	return _c
}

// SetNillableVisible sets the "visible" field if the given value is not nil.
func (_c *MenuCreate) SetNillableVisible(v *int32) *MenuCreate {
	if v != nil {
		_c.SetVisible(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MenuCreate) SetStatus(v int32) *MenuCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MenuCreate) SetNillableStatus(v *int32) *MenuCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPerms sets the "perms" field.
func (_c *MenuCreate) SetPerms(v string) *MenuCreate {
	_c.mutation.SetPerms(v)
	return _c
}

// SetNillablePerms sets the "perms" field if the given value is not nil.
func (_c *MenuCreate) SetNillablePerms(v *string) *MenuCreate {
	if v != nil {
		_c.SetPerms(*v)
	}
	return _c
}

// SetIcon sets the "icon" field.
func (_c *MenuCreate) SetIcon(v string) *MenuCreate {
	_c.mutation.SetIcon(v)
	return _c
}

// SetNillableIcon sets the "icon" field if the given value is not nil.
func (_c *MenuCreate) SetNillableIcon(v *string) *MenuCreate {
	if v != nil {
		_c.SetIcon(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *MenuCreate) SetRemark(v string) *MenuCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *MenuCreate) SetNillableRemark(v *string) *MenuCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MenuCreate) SetID(v int64) *MenuCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MenuMutation object of the builder.
func (_c *MenuCreate) Mutation() *MenuMutation {
	return _c.mutation
}

// Save creates the Menu in the database.
func (_c *MenuCreate) Save(ctx context.Context) (*Menu, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MenuCreate) SaveX(ctx context.Context) *Menu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MenuCreate) defaults() {
	if _, ok := _c.mutation.CreateBy(); !ok {
		v := menu.DefaultCreateBy
		_c.mutation.SetCreateBy(v)
	}
	if _, ok := _c.mutation.UpdateBy(); !ok {
		v := menu.DefaultUpdateBy
		_c.mutation.SetUpdateBy(v)
	}
	if _, ok := _c.mutation.CreatedTime(); !ok {
		v := menu.DefaultCreatedTime()
		_c.mutation.SetCreatedTime(v)
	}
	if _, ok := _c.mutation.UpdatedTime(); !ok {
		v := menu.DefaultUpdatedTime()
		_c.mutation.SetUpdatedTime(v)
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		v := menu.DefaultParentID
		_c.mutation.SetParentID(v)
	}
	if _, ok := _c.mutation.Sort(); !ok {
		v := menu.DefaultSort
		_c.mutation.SetSort(v)
	}
	if _, ok := _c.mutation.Path(); !ok {
		v := menu.DefaultPath
		_c.mutation.SetPath(v)
	}
	if _, ok := _c.mutation.Component(); !ok {
		v := menu.DefaultComponent
		_c.mutation.SetComponent(v)
	}
	if _, ok := _c.mutation.Query(); !ok {
		v := menu.DefaultQuery
		_c.mutation.SetQuery(v)
	}
	if _, ok := _c.mutation.IsFrame(); !ok {
		v := menu.DefaultIsFrame
		_c.mutation.SetIsFrame(v)
	}
	if _, ok := _c.mutation.IsCache(); !ok {
		v := menu.DefaultIsCache
		_c.mutation.SetIsCache(v)
	}
	if _, ok := _c.mutation.MenuType(); !ok {
		v := menu.DefaultMenuType
		_c.mutation.SetMenuType(v)
	}
	if _, ok := _c.mutation.Visible(); !ok {
		v := menu.DefaultVisible
		_c.mutation.SetVisible(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := menu.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Perms(); !ok {
		v := menu.DefaultPerms
		_c.mutation.SetPerms(v)
	}
	if _, ok := _c.mutation.Icon(); !ok {
		v := menu.DefaultIcon
		_c.mutation.SetIcon(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := menu.DefaultRemark
		_c.mutation.SetRemark(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MenuCreate) check() error {
	if _, ok := _c.mutation.CreateBy(); !ok {
		return &ValidationError{Name: "create_by", err: errors.New(`ent: missing required field "Menu.create_by"`)}
	}
	if _, ok := _c.mutation.UpdateBy(); !ok {
		return &ValidationError{Name: "update_by", err: errors.New(`ent: missing required field "Menu.update_by"`)}
	}
	if _, ok := _c.mutation.CreatedTime(); !ok {
		return &ValidationError{Name: "created_time", err: errors.New(`ent: missing required field "Menu.created_time"`)}
	}
	if _, ok := _c.mutation.UpdatedTime(); !ok {
		return &ValidationError{Name: "updated_time", err: errors.New(`ent: missing required field "Menu.updated_time"`)}
	}
	if _, ok := _c.mutation.MenuName(); !ok {
		return &ValidationError{Name: "menu_name", err: errors.New(`ent: missing required field "Menu.menu_name"`)}
	}
	if v, ok := _c.mutation.MenuName(); ok {
		if err := menu.MenuNameValidator(v); err != nil {
			return &ValidationError{Name: "menu_name", err: fmt.Errorf(`ent: validator failed for field "Menu.menu_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ParentID(); !ok {
		return &ValidationError{Name: "parent_id", err: errors.New(`ent: missing required field "Menu.parent_id"`)}
	}
	if _, ok := _c.mutation.Sort(); !ok {
		return &ValidationError{Name: "sort", err: errors.New(`ent: missing required field "Menu.sort"`)}
	}
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "Menu.path"`)}
	}
	if _, ok := _c.mutation.Component(); !ok {
		return &ValidationError{Name: "component", err: errors.New(`ent: missing required field "Menu.component"`)}
	}
	if _, ok := _c.mutation.Query(); !ok {
		return &ValidationError{Name: "query", err: errors.New(`ent: missing required field "Menu.query"`)}
	}
	if _, ok := _c.mutation.IsFrame(); !ok {
		return &ValidationError{Name: "is_frame", err: errors.New(`ent: missing required field "Menu.is_frame"`)}
	}
	if _, ok := _c.mutation.IsCache(); !ok {
		return &ValidationError{Name: "is_cache", err: errors.New(`ent: missing required field "Menu.is_cache"`)}
	}
	if _, ok := _c.mutation.MenuType(); !ok {
		return &ValidationError{Name: "menu_type", err: errors.New(`ent: missing required field "Menu.menu_type"`)}
	}
	if _, ok := _c.mutation.Visible(); !ok {
		return &ValidationError{Name: "visible", err: errors.New(`ent: missing required field "Menu.visible"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Menu.status"`)}
	}
	if _, ok := _c.mutation.Perms(); !ok {
		return &ValidationError{Name: "perms", err: errors.New(`ent: missing required field "Menu.perms"`)}
	}
	if _, ok := _c.mutation.Icon(); !ok {
		return &ValidationError{Name: "icon", err: errors.New(`ent: missing required field "Menu.icon"`)}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "Menu.remark"`)}
	}
	return nil
}

func (_c *MenuCreate) sqlSave(ctx context.Context) (*Menu, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MenuCreate) createSpec() (*Menu, *sqlgraph.CreateSpec) {
	var (
		_node = &Menu{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(menu.Table, sqlgraph.NewFieldSpec(menu.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(menu.FieldCreateBy, field.TypeInt64, value)
		_node.CreateBy = value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(menu.FieldUpdateBy, field.TypeInt64, value)
		_node.UpdateBy = value
	}
	if value, ok := _c.mutation.CreatedTime(); ok {
		_spec.SetField(menu.FieldCreatedTime, field.TypeTime, value)
		_node.CreatedTime = value
	}
	if value, ok := _c.mutation.UpdatedTime(); ok {
		_spec.SetField(menu.FieldUpdatedTime, field.TypeTime, value)
		_node.UpdatedTime = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(menu.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.MenuName(); ok {
		_spec.SetField(menu.FieldMenuName, field.TypeString, value)
		_node.MenuName = value
	}
	if value, ok := _c.mutation.ParentID(); ok {
		_spec.SetField(menu.FieldParentID, field.TypeInt64, value)
		_node.ParentID = value
	}
	if value, ok := _c.mutation.Sort(); ok {
		_spec.SetField(menu.FieldSort, field.TypeInt64, value)
		_node.Sort = value
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(menu.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.Component(); ok {
		_spec.SetField(menu.FieldComponent, field.TypeString, value)
		_node.Component = value
	}
	if value, ok := _c.mutation.Query(); ok {
		_spec.SetField(menu.FieldQuery, field.TypeString, value)
		_node.Query = value
	}
	if value, ok := _c.mutation.IsFrame(); ok {
		_spec.SetField(menu.FieldIsFrame, field.TypeInt32, value)
		_node.IsFrame = value
	}
	if value, ok := _c.mutation.IsCache(); ok {
		_spec.SetField(menu.FieldIsCache, field.TypeInt32, value)
		_node.IsCache = value
	}
	if value, ok := _c.mutation.MenuType(); ok {
		_spec.SetField(menu.FieldMenuType, field.TypeInt32, value)
		_node.MenuType = value
	}
	if value, ok := _c.mutation.Visible(); ok {
		_spec.SetField(menu.FieldVisible, field.TypeInt32, value)
		_node.Visible = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(menu.FieldStatus, field.TypeInt32, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Perms(); ok {
		_spec.SetField(menu.FieldPerms, field.TypeString, value)
		_node.Perms = value
	}
	if value, ok := _c.mutation.Icon(); ok {
		_spec.SetField(menu.FieldIcon, field.TypeString, value)
		_node.Icon = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(menu.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	return _node, _spec
}

// MenuCreateBulk is the builder for creating many Menu entities in bulk.
type MenuCreateBulk struct {
	config
	err      error
	builders []*MenuCreate
}

// Save creates the Menu entities in the database.
func (_c *MenuCreateBulk) Save(ctx context.Context) ([]*Menu, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Menu, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MenuMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MenuCreateBulk) SaveX(ctx context.Context) []*Menu {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MenuCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MenuCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
