// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/attachment"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/authclient"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/casbinrule"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/dictdata"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/loginlog"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/menu"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/operlog"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/org"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/role"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/rolemenu"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/schema"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/storageenv"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/systemconfig"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/user"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/userrole"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescEnvID is the schema descriptor for env_id field.
	attachmentDescEnvID := attachmentFields[1].Descriptor()
	// attachment.DefaultEnvID holds the default value on creation for the env_id field.
	attachment.DefaultEnvID = attachmentDescEnvID.Default.(int64)
	// attachmentDescFileName is the schema descriptor for file_name field.
	attachmentDescFileName := attachmentFields[2].Descriptor()
	// attachment.FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	attachment.FileNameValidator = attachmentDescFileName.Validators[0].(func(string) error)
	// attachmentDescFileKey is the schema descriptor for file_key field.
	attachmentDescFileKey := attachmentFields[3].Descriptor()
	// attachment.DefaultFileKey holds the default value on creation for the file_key field.
	attachment.DefaultFileKey = attachmentDescFileKey.Default.(string)
	// attachmentDescFileSize is the schema descriptor for file_size field.
	attachmentDescFileSize := attachmentFields[4].Descriptor()
	// attachment.DefaultFileSize holds the default value on creation for the file_size field.
	attachment.DefaultFileSize = attachmentDescFileSize.Default.(int64)
	// attachmentDescFileType is the schema descriptor for file_type field.
	attachmentDescFileType := attachmentFields[5].Descriptor()
	// attachment.DefaultFileType holds the default value on creation for the file_type field.
	attachment.DefaultFileType = attachmentDescFileType.Default.(string)
	// attachmentDescFileExt is the schema descriptor for file_ext field.
	attachmentDescFileExt := attachmentFields[6].Descriptor()
	// attachment.DefaultFileExt holds the default value on creation for the file_ext field.
	attachment.DefaultFileExt = attachmentDescFileExt.Default.(string)
	// attachmentDescBusinessType is the schema descriptor for business_type field.
	attachmentDescBusinessType := attachmentFields[7].Descriptor()
	// attachment.DefaultBusinessType holds the default value on creation for the business_type field.
	attachment.DefaultBusinessType = attachmentDescBusinessType.Default.(string)
	// attachmentDescBusinessID is the schema descriptor for business_id field.
	attachmentDescBusinessID := attachmentFields[8].Descriptor()
	// attachment.DefaultBusinessID holds the default value on creation for the business_id field.
	attachment.DefaultBusinessID = attachmentDescBusinessID.Default.(string)
	// attachmentDescBusinessField is the schema descriptor for business_field field.
	attachmentDescBusinessField := attachmentFields[9].Descriptor()
	// attachment.DefaultBusinessField holds the default value on creation for the business_field field.
	attachment.DefaultBusinessField = attachmentDescBusinessField.Default.(string)
	// attachmentDescIsPublic is the schema descriptor for is_public field.
	attachmentDescIsPublic := attachmentFields[10].Descriptor()
	// attachment.DefaultIsPublic holds the default value on creation for the is_public field.
	attachment.DefaultIsPublic = attachmentDescIsPublic.Default.(bool)
	// attachmentDescAccessURL is the schema descriptor for access_url field.
	attachmentDescAccessURL := attachmentFields[11].Descriptor()
	// attachment.DefaultAccessURL holds the default value on creation for the access_url field.
	attachment.DefaultAccessURL = attachmentDescAccessURL.Default.(string)
	// attachmentDescStatus is the schema descriptor for status field.
	attachmentDescStatus := attachmentFields[13].Descriptor()
	// attachment.DefaultStatus holds the default value on creation for the status field.
	attachment.DefaultStatus = attachmentDescStatus.Default.(int32)
	// attachmentDescCreateBy is the schema descriptor for create_by field.
	attachmentDescCreateBy := attachmentFields[15].Descriptor()
	// attachment.DefaultCreateBy holds the default value on creation for the create_by field.
	attachment.DefaultCreateBy = attachmentDescCreateBy.Default.(int64)
	// attachmentDescCreateTime is the schema descriptor for create_time field.
	attachmentDescCreateTime := attachmentFields[16].Descriptor()
	// attachment.DefaultCreateTime holds the default value on creation for the create_time field.
	attachment.DefaultCreateTime = attachmentDescCreateTime.Default.(func() time.Time)
	// attachmentDescUpdateTime is the schema descriptor for update_time field.
	attachmentDescUpdateTime := attachmentFields[17].Descriptor()
	// attachment.DefaultUpdateTime holds the default value on creation for the update_time field.
	attachment.DefaultUpdateTime = attachmentDescUpdateTime.Default.(func() time.Time)
	// attachment.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	attachment.UpdateDefaultUpdateTime = attachmentDescUpdateTime.UpdateDefault.(func() time.Time)
	authclientMixin := schema.AuthClient{}.Mixin()
	authclientMixinFields0 := authclientMixin[0].Fields()
	_ = authclientMixinFields0
	authclientFields := schema.AuthClient{}.Fields()
	_ = authclientFields
	// authclientDescCreateBy is the schema descriptor for create_by field.
	authclientDescCreateBy := authclientMixinFields0[0].Descriptor()
	// authclient.DefaultCreateBy holds the default value on creation for the create_by field.
	authclient.DefaultCreateBy = authclientDescCreateBy.Default.(int64)
	// authclientDescUpdateBy is the schema descriptor for update_by field.
	authclientDescUpdateBy := authclientMixinFields0[1].Descriptor()
	// authclient.DefaultUpdateBy holds the default value on creation for the update_by field.
	authclient.DefaultUpdateBy = authclientDescUpdateBy.Default.(int64)
	// authclientDescCreatedTime is the schema descriptor for created_time field.
	authclientDescCreatedTime := authclientMixinFields0[2].Descriptor()
	// authclient.DefaultCreatedTime holds the default value on creation for the created_time field.
	authclient.DefaultCreatedTime = authclientDescCreatedTime.Default.(func() time.Time)
	// authclientDescUpdatedTime is the schema descriptor for updated_time field.
	authclientDescUpdatedTime := authclientMixinFields0[3].Descriptor()
	// authclient.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	authclient.DefaultUpdatedTime = authclientDescUpdatedTime.Default.(func() time.Time)
	// authclient.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	authclient.UpdateDefaultUpdatedTime = authclientDescUpdatedTime.UpdateDefault.(func() time.Time)
	// authclientDescClientID is the schema descriptor for client_id field.
	authclientDescClientID := authclientFields[0].Descriptor()
	// authclient.ClientIDValidator is a validator for the "client_id" field. It is called by the builders before save.
	authclient.ClientIDValidator = authclientDescClientID.Validators[0].(func(string) error)
	// authclientDescClientKey is the schema descriptor for client_key field.
	authclientDescClientKey := authclientFields[1].Descriptor()
	// authclient.ClientKeyValidator is a validator for the "client_key" field. It is called by the builders before save.
	authclient.ClientKeyValidator = authclientDescClientKey.Validators[0].(func(string) error)
	// authclientDescClientSecret is the schema descriptor for client_secret field.
	authclientDescClientSecret := authclientFields[2].Descriptor()
	// authclient.ClientSecretValidator is a validator for the "client_secret" field. It is called by the builders before save.
	authclient.ClientSecretValidator = authclientDescClientSecret.Validators[0].(func(string) error)
	// authclientDescGrantType is the schema descriptor for grant_type field.
	authclientDescGrantType := authclientFields[3].Descriptor()
	// authclient.DefaultGrantType holds the default value on creation for the grant_type field.
	authclient.DefaultGrantType = authclientDescGrantType.Default.(string)
	// authclientDescDeviceType is the schema descriptor for device_type field.
	authclientDescDeviceType := authclientFields[4].Descriptor()
	// authclient.DefaultDeviceType holds the default value on creation for the device_type field.
	authclient.DefaultDeviceType = authclientDescDeviceType.Default.(string)
	// authclientDescStatus is the schema descriptor for status field.
	authclientDescStatus := authclientFields[5].Descriptor()
	// authclient.DefaultStatus holds the default value on creation for the status field.
	authclient.DefaultStatus = authclientDescStatus.Default.(int32)
	// authclientDescTimeout is the schema descriptor for timeout field.
	authclientDescTimeout := authclientFields[6].Descriptor()
	// authclient.DefaultTimeout holds the default value on creation for the timeout field.
	authclient.DefaultTimeout = authclientDescTimeout.Default.(int64)
	// authclientDescActiveTimeout is the schema descriptor for active_timeout field.
	authclientDescActiveTimeout := authclientFields[7].Descriptor()
	// authclient.DefaultActiveTimeout holds the default value on creation for the active_timeout field.
	authclient.DefaultActiveTimeout = authclientDescActiveTimeout.Default.(int64)
	// authclientDescRemark is the schema descriptor for remark field.
	authclientDescRemark := authclientFields[8].Descriptor()
	// authclient.DefaultRemark holds the default value on creation for the remark field.
	authclient.DefaultRemark = authclientDescRemark.Default.(string)
	casbinruleFields := schema.CasbinRule{}.Fields()
	_ = casbinruleFields
	// casbinruleDescPtype is the schema descriptor for ptype field.
	casbinruleDescPtype := casbinruleFields[1].Descriptor()
	// casbinrule.DefaultPtype holds the default value on creation for the ptype field.
	casbinrule.DefaultPtype = casbinruleDescPtype.Default.(string)
	// casbinruleDescV0 is the schema descriptor for v0 field.
	casbinruleDescV0 := casbinruleFields[2].Descriptor()
	// casbinrule.DefaultV0 holds the default value on creation for the v0 field.
	casbinrule.DefaultV0 = casbinruleDescV0.Default.(string)
	// casbinruleDescV1 is the schema descriptor for v1 field.
	casbinruleDescV1 := casbinruleFields[3].Descriptor()
	// casbinrule.DefaultV1 holds the default value on creation for the v1 field.
	casbinrule.DefaultV1 = casbinruleDescV1.Default.(string)
	// casbinruleDescV2 is the schema descriptor for v2 field.
	casbinruleDescV2 := casbinruleFields[4].Descriptor()
	// casbinrule.DefaultV2 holds the default value on creation for the v2 field.
	casbinrule.DefaultV2 = casbinruleDescV2.Default.(string)
	// casbinruleDescV3 is the schema descriptor for v3 field.
	casbinruleDescV3 := casbinruleFields[5].Descriptor()
	// casbinrule.DefaultV3 holds the default value on creation for the v3 field.
	casbinrule.DefaultV3 = casbinruleDescV3.Default.(string)
	// casbinruleDescV4 is the schema descriptor for v4 field.
	casbinruleDescV4 := casbinruleFields[6].Descriptor()
	// casbinrule.DefaultV4 holds the default value on creation for the v4 field.
	casbinrule.DefaultV4 = casbinruleDescV4.Default.(string)
	// casbinruleDescV5 is the schema descriptor for v5 field.
	casbinruleDescV5 := casbinruleFields[7].Descriptor()
	// casbinrule.DefaultV5 holds the default value on creation for the v5 field.
	casbinrule.DefaultV5 = casbinruleDescV5.Default.(string)
	dictdataMixin := schema.DictData{}.Mixin()
	dictdataMixinFields0 := dictdataMixin[0].Fields()
	_ = dictdataMixinFields0
	dictdataFields := schema.DictData{}.Fields()
	_ = dictdataFields
	// dictdataDescCreateBy is the schema descriptor for create_by field.
	dictdataDescCreateBy := dictdataMixinFields0[0].Descriptor()
	// dictdata.DefaultCreateBy holds the default value on creation for the create_by field.
	dictdata.DefaultCreateBy = dictdataDescCreateBy.Default.(int64)
	// dictdataDescUpdateBy is the schema descriptor for update_by field.
	dictdataDescUpdateBy := dictdataMixinFields0[1].Descriptor()
	// dictdata.DefaultUpdateBy holds the default value on creation for the update_by field.
	dictdata.DefaultUpdateBy = dictdataDescUpdateBy.Default.(int64)
	// dictdataDescCreatedTime is the schema descriptor for created_time field.
	dictdataDescCreatedTime := dictdataMixinFields0[2].Descriptor()
	// dictdata.DefaultCreatedTime holds the default value on creation for the created_time field.
	dictdata.DefaultCreatedTime = dictdataDescCreatedTime.Default.(func() time.Time)
	// dictdataDescUpdatedTime is the schema descriptor for updated_time field.
	dictdataDescUpdatedTime := dictdataMixinFields0[3].Descriptor()
	// dictdata.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	dictdata.DefaultUpdatedTime = dictdataDescUpdatedTime.Default.(func() time.Time)
	// dictdata.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	dictdata.UpdateDefaultUpdatedTime = dictdataDescUpdatedTime.UpdateDefault.(func() time.Time)
	// dictdataDescParentID is the schema descriptor for parent_id field.
	dictdataDescParentID := dictdataFields[1].Descriptor()
	// dictdata.DefaultParentID holds the default value on creation for the parent_id field.
	dictdata.DefaultParentID = dictdataDescParentID.Default.(int64)
	// dictdataDescSort is the schema descriptor for sort field.
	dictdataDescSort := dictdataFields[2].Descriptor()
	// dictdata.DefaultSort holds the default value on creation for the sort field.
	dictdata.DefaultSort = dictdataDescSort.Default.(int64)
	// dictdataDescDictLabel is the schema descriptor for dict_label field.
	dictdataDescDictLabel := dictdataFields[3].Descriptor()
	// dictdata.DefaultDictLabel holds the default value on creation for the dict_label field.
	dictdata.DefaultDictLabel = dictdataDescDictLabel.Default.(string)
	// dictdataDescDictValue is the schema descriptor for dict_value field.
	dictdataDescDictValue := dictdataFields[4].Descriptor()
	// dictdata.DefaultDictValue holds the default value on creation for the dict_value field.
	dictdata.DefaultDictValue = dictdataDescDictValue.Default.(string)
	// dictdataDescDictType is the schema descriptor for dict_type field.
	dictdataDescDictType := dictdataFields[5].Descriptor()
	// dictdata.DefaultDictType holds the default value on creation for the dict_type field.
	dictdata.DefaultDictType = dictdataDescDictType.Default.(string)
	// dictdataDescIsDefault is the schema descriptor for is_default field.
	dictdataDescIsDefault := dictdataFields[6].Descriptor()
	// dictdata.DefaultIsDefault holds the default value on creation for the is_default field.
	dictdata.DefaultIsDefault = dictdataDescIsDefault.Default.(bool)
	// dictdataDescStatus is the schema descriptor for status field.
	dictdataDescStatus := dictdataFields[7].Descriptor()
	// dictdata.DefaultStatus holds the default value on creation for the status field.
	dictdata.DefaultStatus = dictdataDescStatus.Default.(int32)
	// dictdataDescRemark is the schema descriptor for remark field.
	dictdataDescRemark := dictdataFields[8].Descriptor()
	// dictdata.DefaultRemark holds the default value on creation for the remark field.
	dictdata.DefaultRemark = dictdataDescRemark.Default.(string)
	loginlogFields := schema.LoginLog{}.Fields()
	_ = loginlogFields
	// loginlogDescUserName is the schema descriptor for user_name field.
	loginlogDescUserName := loginlogFields[1].Descriptor()
	// loginlog.DefaultUserName holds the default value on creation for the user_name field.
	loginlog.DefaultUserName = loginlogDescUserName.Default.(string)
	// loginlogDescIpaddr is the schema descriptor for ipaddr field.
	loginlogDescIpaddr := loginlogFields[2].Descriptor()
	// loginlog.DefaultIpaddr holds the default value on creation for the ipaddr field.
	loginlog.DefaultIpaddr = loginlogDescIpaddr.Default.(string)
	// loginlogDescLoginLocation is the schema descriptor for login_location field.
	loginlogDescLoginLocation := loginlogFields[3].Descriptor()
	// loginlog.DefaultLoginLocation holds the default value on creation for the login_location field.
	loginlog.DefaultLoginLocation = loginlogDescLoginLocation.Default.(string)
	// loginlogDescBrowser is the schema descriptor for browser field.
	loginlogDescBrowser := loginlogFields[4].Descriptor()
	// loginlog.DefaultBrowser holds the default value on creation for the browser field.
	loginlog.DefaultBrowser = loginlogDescBrowser.Default.(string)
	// loginlogDescOs is the schema descriptor for os field.
	loginlogDescOs := loginlogFields[5].Descriptor()
	// loginlog.DefaultOs holds the default value on creation for the os field.
	loginlog.DefaultOs = loginlogDescOs.Default.(string)
	// loginlogDescStatus is the schema descriptor for status field.
	loginlogDescStatus := loginlogFields[6].Descriptor()
	// loginlog.DefaultStatus holds the default value on creation for the status field.
	loginlog.DefaultStatus = loginlogDescStatus.Default.(int32)
	// loginlogDescMsg is the schema descriptor for msg field.
	loginlogDescMsg := loginlogFields[7].Descriptor()
	// loginlog.DefaultMsg holds the default value on creation for the msg field.
	loginlog.DefaultMsg = loginlogDescMsg.Default.(string)
	// loginlogDescLoginTime is the schema descriptor for login_time field.
	loginlogDescLoginTime := loginlogFields[8].Descriptor()
	// loginlog.DefaultLoginTime holds the default value on creation for the login_time field.
	loginlog.DefaultLoginTime = loginlogDescLoginTime.Default.(func() time.Time)
	// loginlogDescClientID is the schema descriptor for client_id field.
	loginlogDescClientID := loginlogFields[9].Descriptor()
	// loginlog.DefaultClientID holds the default value on creation for the client_id field.
	loginlog.DefaultClientID = loginlogDescClientID.Default.(string)
	menuMixin := schema.Menu{}.Mixin()
	menuMixinFields0 := menuMixin[0].Fields()
	_ = menuMixinFields0
	menuFields := schema.Menu{}.Fields()
	_ = menuFields
	// menuDescCreateBy is the schema descriptor for create_by field.
	menuDescCreateBy := menuMixinFields0[0].Descriptor()
	// menu.DefaultCreateBy holds the default value on creation for the create_by field.
	menu.DefaultCreateBy = menuDescCreateBy.Default.(int64)
	// menuDescUpdateBy is the schema descriptor for update_by field.
	menuDescUpdateBy := menuMixinFields0[1].Descriptor()
	// menu.DefaultUpdateBy holds the default value on creation for the update_by field.
	menu.DefaultUpdateBy = menuDescUpdateBy.Default.(int64)
	// menuDescCreatedTime is the schema descriptor for created_time field.
	menuDescCreatedTime := menuMixinFields0[2].Descriptor()
	// menu.DefaultCreatedTime holds the default value on creation for the created_time field.
	menu.DefaultCreatedTime = menuDescCreatedTime.Default.(func() time.Time)
	// menuDescUpdatedTime is the schema descriptor for updated_time field.
	menuDescUpdatedTime := menuMixinFields0[3].Descriptor()
	// menu.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	menu.DefaultUpdatedTime = menuDescUpdatedTime.Default.(func() time.Time)
	// menu.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	menu.UpdateDefaultUpdatedTime = menuDescUpdatedTime.UpdateDefault.(func() time.Time)
	// menuDescMenuName is the schema descriptor for menu_name field.
	menuDescMenuName := menuFields[1].Descriptor()
	// menu.MenuNameValidator is a validator for the "menu_name" field. It is called by the builders before save.
	menu.MenuNameValidator = menuDescMenuName.Validators[0].(func(string) error)
	// menuDescParentID is the schema descriptor for parent_id field.
	menuDescParentID := menuFields[2].Descriptor()
	// menu.DefaultParentID holds the default value on creation for the parent_id field.
	menu.DefaultParentID = menuDescParentID.Default.(int64)
	// menuDescSort is the schema descriptor for sort field.
	menuDescSort := menuFields[3].Descriptor()
	// menu.DefaultSort holds the default value on creation for the sort field.
	menu.DefaultSort = menuDescSort.Default.(int64)
	// menuDescPath is the schema descriptor for path field.
	menuDescPath := menuFields[4].Descriptor()
	// menu.DefaultPath holds the default value on creation for the path field.
	menu.DefaultPath = menuDescPath.Default.(string)
	// menuDescComponent is the schema descriptor for component field.
	menuDescComponent := menuFields[5].Descriptor()
	// menu.DefaultComponent holds the default value on creation for the component field.
	menu.DefaultComponent = menuDescComponent.Default.(string)
	// menuDescQuery is the schema descriptor for query field.
	menuDescQuery := menuFields[6].Descriptor()
	// menu.DefaultQuery holds the default value on creation for the query field.
	menu.DefaultQuery = menuDescQuery.Default.(string)
	// menuDescIsFrame is the schema descriptor for is_frame field.
	menuDescIsFrame := menuFields[7].Descriptor()
	// menu.DefaultIsFrame holds the default value on creation for the is_frame field.
	menu.DefaultIsFrame = menuDescIsFrame.Default.(int32)
	// menuDescIsCache is the schema descriptor for is_cache field.
	menuDescIsCache := menuFields[8].Descriptor()
	// menu.DefaultIsCache holds the default value on creation for the is_cache field.
	menu.DefaultIsCache = menuDescIsCache.Default.(int32)
	// menuDescMenuType is the schema descriptor for menu_type field.
	menuDescMenuType := menuFields[9].Descriptor()
	// menu.DefaultMenuType holds the default value on creation for the menu_type field.
	menu.DefaultMenuType = menuDescMenuType.Default.(int32)
	// menuDescVisible is the schema descriptor for visible field.
	menuDescVisible := menuFields[10].Descriptor()
	// menu.DefaultVisible holds the default value on creation for the visible field.
	menu.DefaultVisible = menuDescVisible.Default.(int32)
	// menuDescStatus is the schema descriptor for status field.
	menuDescStatus := menuFields[11].Descriptor()
	// menu.DefaultStatus holds the default value on creation for the status field.
	menu.DefaultStatus = menuDescStatus.Default.(int32)
	// menuDescPerms is the schema descriptor for perms field.
	menuDescPerms := menuFields[12].Descriptor()
	// menu.DefaultPerms holds the default value on creation for the perms field.
	menu.DefaultPerms = menuDescPerms.Default.(string)
	// menuDescIcon is the schema descriptor for icon field.
	menuDescIcon := menuFields[13].Descriptor()
	// menu.DefaultIcon holds the default value on creation for the icon field.
	menu.DefaultIcon = menuDescIcon.Default.(string)
	// menuDescRemark is the schema descriptor for remark field.
	menuDescRemark := menuFields[14].Descriptor()
	// menu.DefaultRemark holds the default value on creation for the remark field.
	menu.DefaultRemark = menuDescRemark.Default.(string)
	operlogFields := schema.OperLog{}.Fields()
	_ = operlogFields
	// operlogDescTitle is the schema descriptor for title field.
	operlogDescTitle := operlogFields[1].Descriptor()
	// operlog.DefaultTitle holds the default value on creation for the title field.
	operlog.DefaultTitle = operlogDescTitle.Default.(string)
	// operlogDescBusinessType is the schema descriptor for business_type field.
	operlogDescBusinessType := operlogFields[2].Descriptor()
	// operlog.DefaultBusinessType holds the default value on creation for the business_type field.
	operlog.DefaultBusinessType = operlogDescBusinessType.Default.(string)
	// operlogDescMethod is the schema descriptor for method field.
	operlogDescMethod := operlogFields[3].Descriptor()
	// operlog.DefaultMethod holds the default value on creation for the method field.
	operlog.DefaultMethod = operlogDescMethod.Default.(string)
	// operlogDescRequestMethod is the schema descriptor for request_method field.
	operlogDescRequestMethod := operlogFields[4].Descriptor()
	// operlog.DefaultRequestMethod holds the default value on creation for the request_method field.
	operlog.DefaultRequestMethod = operlogDescRequestMethod.Default.(string)
	// operlogDescDeviceType is the schema descriptor for device_type field.
	operlogDescDeviceType := operlogFields[5].Descriptor()
	// operlog.DefaultDeviceType holds the default value on creation for the device_type field.
	operlog.DefaultDeviceType = operlogDescDeviceType.Default.(string)
	// operlogDescOperName is the schema descriptor for oper_name field.
	operlogDescOperName := operlogFields[6].Descriptor()
	// operlog.DefaultOperName holds the default value on creation for the oper_name field.
	operlog.DefaultOperName = operlogDescOperName.Default.(string)
	// operlogDescOperURL is the schema descriptor for oper_url field.
	operlogDescOperURL := operlogFields[7].Descriptor()
	// operlog.DefaultOperURL holds the default value on creation for the oper_url field.
	operlog.DefaultOperURL = operlogDescOperURL.Default.(string)
	// operlogDescOperIP is the schema descriptor for oper_ip field.
	operlogDescOperIP := operlogFields[8].Descriptor()
	// operlog.DefaultOperIP holds the default value on creation for the oper_ip field.
	operlog.DefaultOperIP = operlogDescOperIP.Default.(string)
	// operlogDescOperLocation is the schema descriptor for oper_location field.
	operlogDescOperLocation := operlogFields[9].Descriptor()
	// operlog.DefaultOperLocation holds the default value on creation for the oper_location field.
	operlog.DefaultOperLocation = operlogDescOperLocation.Default.(string)
	// operlogDescOperParam is the schema descriptor for oper_param field.
	operlogDescOperParam := operlogFields[10].Descriptor()
	// operlog.DefaultOperParam holds the default value on creation for the oper_param field.
	operlog.DefaultOperParam = operlogDescOperParam.Default.(string)
	// operlogDescJSONResult is the schema descriptor for json_result field.
	operlogDescJSONResult := operlogFields[11].Descriptor()
	// operlog.DefaultJSONResult holds the default value on creation for the json_result field.
	operlog.DefaultJSONResult = operlogDescJSONResult.Default.(string)
	// operlogDescStatus is the schema descriptor for status field.
	operlogDescStatus := operlogFields[12].Descriptor()
	// operlog.DefaultStatus holds the default value on creation for the status field.
	operlog.DefaultStatus = operlogDescStatus.Default.(string)
	// operlogDescErrorMsg is the schema descriptor for error_msg field.
	operlogDescErrorMsg := operlogFields[13].Descriptor()
	// operlog.DefaultErrorMsg holds the default value on creation for the error_msg field.
	operlog.DefaultErrorMsg = operlogDescErrorMsg.Default.(string)
	// operlogDescOperTime is the schema descriptor for oper_time field.
	operlogDescOperTime := operlogFields[14].Descriptor()
	// operlog.DefaultOperTime holds the default value on creation for the oper_time field.
	operlog.DefaultOperTime = operlogDescOperTime.Default.(func() time.Time)
	// operlogDescCostTime is the schema descriptor for cost_time field.
	operlogDescCostTime := operlogFields[15].Descriptor()
	// operlog.DefaultCostTime holds the default value on creation for the cost_time field.
	operlog.DefaultCostTime = operlogDescCostTime.Default.(int64)
	// operlogDescUserAgent is the schema descriptor for user_agent field.
	operlogDescUserAgent := operlogFields[16].Descriptor()
	// operlog.DefaultUserAgent holds the default value on creation for the user_agent field.
	operlog.DefaultUserAgent = operlogDescUserAgent.Default.(string)
	orgMixin := schema.Org{}.Mixin()
	orgMixinFields0 := orgMixin[0].Fields()
	_ = orgMixinFields0
	orgFields := schema.Org{}.Fields()
	_ = orgFields
	// orgDescCreateBy is the schema descriptor for create_by field.
	orgDescCreateBy := orgMixinFields0[0].Descriptor()
	// org.DefaultCreateBy holds the default value on creation for the create_by field.
	org.DefaultCreateBy = orgDescCreateBy.Default.(int64)
	// orgDescUpdateBy is the schema descriptor for update_by field.
	orgDescUpdateBy := orgMixinFields0[1].Descriptor()
	// org.DefaultUpdateBy holds the default value on creation for the update_by field.
	org.DefaultUpdateBy = orgDescUpdateBy.Default.(int64)
	// orgDescCreatedTime is the schema descriptor for created_time field.
	orgDescCreatedTime := orgMixinFields0[2].Descriptor()
	// org.DefaultCreatedTime holds the default value on creation for the created_time field.
	org.DefaultCreatedTime = orgDescCreatedTime.Default.(func() time.Time)
	// orgDescUpdatedTime is the schema descriptor for updated_time field.
	orgDescUpdatedTime := orgMixinFields0[3].Descriptor()
	// org.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	org.DefaultUpdatedTime = orgDescUpdatedTime.Default.(func() time.Time)
	// org.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	org.UpdateDefaultUpdatedTime = orgDescUpdatedTime.UpdateDefault.(func() time.Time)
	// orgDescParentID is the schema descriptor for parent_id field.
	orgDescParentID := orgFields[1].Descriptor()
	// org.DefaultParentID holds the default value on creation for the parent_id field.
	org.DefaultParentID = orgDescParentID.Default.(int64)
	// orgDescAncestors is the schema descriptor for ancestors field.
	orgDescAncestors := orgFields[2].Descriptor()
	// org.DefaultAncestors holds the default value on creation for the ancestors field.
	org.DefaultAncestors = orgDescAncestors.Default.(string)
	// orgDescOrgName is the schema descriptor for org_name field.
	orgDescOrgName := orgFields[3].Descriptor()
	// org.OrgNameValidator is a validator for the "org_name" field. It is called by the builders before save.
	org.OrgNameValidator = orgDescOrgName.Validators[0].(func(string) error)
	// orgDescOrgCode is the schema descriptor for org_code field.
	orgDescOrgCode := orgFields[4].Descriptor()
	// org.DefaultOrgCode holds the default value on creation for the org_code field.
	org.DefaultOrgCode = orgDescOrgCode.Default.(string)
	// orgDescOrgType is the schema descriptor for org_type field.
	orgDescOrgType := orgFields[5].Descriptor()
	// org.DefaultOrgType holds the default value on creation for the org_type field.
	org.DefaultOrgType = orgDescOrgType.Default.(string)
	// orgDescLeader is the schema descriptor for leader field.
	orgDescLeader := orgFields[6].Descriptor()
	// org.DefaultLeader holds the default value on creation for the leader field.
	org.DefaultLeader = orgDescLeader.Default.(string)
	// orgDescPhone is the schema descriptor for phone field.
	orgDescPhone := orgFields[7].Descriptor()
	// org.DefaultPhone holds the default value on creation for the phone field.
	org.DefaultPhone = orgDescPhone.Default.(string)
	// orgDescEmail is the schema descriptor for email field.
	orgDescEmail := orgFields[8].Descriptor()
	// org.DefaultEmail holds the default value on creation for the email field.
	org.DefaultEmail = orgDescEmail.Default.(string)
	// orgDescStatus is the schema descriptor for status field.
	orgDescStatus := orgFields[9].Descriptor()
	// org.DefaultStatus holds the default value on creation for the status field.
	org.DefaultStatus = orgDescStatus.Default.(int32)
	// orgDescSort is the schema descriptor for sort field.
	orgDescSort := orgFields[10].Descriptor()
	// org.DefaultSort holds the default value on creation for the sort field.
	org.DefaultSort = orgDescSort.Default.(int64)
	// orgDescRemark is the schema descriptor for remark field.
	orgDescRemark := orgFields[11].Descriptor()
	// org.DefaultRemark holds the default value on creation for the remark field.
	org.DefaultRemark = orgDescRemark.Default.(string)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreateBy is the schema descriptor for create_by field.
	roleDescCreateBy := roleMixinFields0[0].Descriptor()
	// role.DefaultCreateBy holds the default value on creation for the create_by field.
	role.DefaultCreateBy = roleDescCreateBy.Default.(int64)
	// roleDescUpdateBy is the schema descriptor for update_by field.
	roleDescUpdateBy := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdateBy holds the default value on creation for the update_by field.
	role.DefaultUpdateBy = roleDescUpdateBy.Default.(int64)
	// roleDescCreatedTime is the schema descriptor for created_time field.
	roleDescCreatedTime := roleMixinFields0[2].Descriptor()
	// role.DefaultCreatedTime holds the default value on creation for the created_time field.
	role.DefaultCreatedTime = roleDescCreatedTime.Default.(func() time.Time)
	// roleDescUpdatedTime is the schema descriptor for updated_time field.
	roleDescUpdatedTime := roleMixinFields0[3].Descriptor()
	// role.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	role.DefaultUpdatedTime = roleDescUpdatedTime.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	role.UpdateDefaultUpdatedTime = roleDescUpdatedTime.UpdateDefault.(func() time.Time)
	// roleDescRoleKey is the schema descriptor for role_key field.
	roleDescRoleKey := roleFields[1].Descriptor()
	// role.RoleKeyValidator is a validator for the "role_key" field. It is called by the builders before save.
	role.RoleKeyValidator = roleDescRoleKey.Validators[0].(func(string) error)
	// roleDescRoleName is the schema descriptor for role_name field.
	roleDescRoleName := roleFields[2].Descriptor()
	// role.RoleNameValidator is a validator for the "role_name" field. It is called by the builders before save.
	role.RoleNameValidator = roleDescRoleName.Validators[0].(func(string) error)
	// roleDescSort is the schema descriptor for sort field.
	roleDescSort := roleFields[3].Descriptor()
	// role.DefaultSort holds the default value on creation for the sort field.
	role.DefaultSort = roleDescSort.Default.(int64)
	// roleDescStatus is the schema descriptor for status field.
	roleDescStatus := roleFields[4].Descriptor()
	// role.DefaultStatus holds the default value on creation for the status field.
	role.DefaultStatus = roleDescStatus.Default.(int32)
	// roleDescDataScope is the schema descriptor for data_scope field.
	roleDescDataScope := roleFields[5].Descriptor()
	// role.DefaultDataScope holds the default value on creation for the data_scope field.
	role.DefaultDataScope = roleDescDataScope.Default.(int32)
	// roleDescIsSystem is the schema descriptor for is_system field.
	roleDescIsSystem := roleFields[6].Descriptor()
	// role.DefaultIsSystem holds the default value on creation for the is_system field.
	role.DefaultIsSystem = roleDescIsSystem.Default.(bool)
	// roleDescRemark is the schema descriptor for remark field.
	roleDescRemark := roleFields[7].Descriptor()
	// role.DefaultRemark holds the default value on creation for the remark field.
	role.DefaultRemark = roleDescRemark.Default.(string)
	rolemenuMixin := schema.RoleMenu{}.Mixin()
	rolemenuMixinFields0 := rolemenuMixin[0].Fields()
	_ = rolemenuMixinFields0
	rolemenuFields := schema.RoleMenu{}.Fields()
	_ = rolemenuFields
	// rolemenuDescCreateBy is the schema descriptor for create_by field.
	rolemenuDescCreateBy := rolemenuMixinFields0[0].Descriptor()
	// rolemenu.DefaultCreateBy holds the default value on creation for the create_by field.
	rolemenu.DefaultCreateBy = rolemenuDescCreateBy.Default.(int64)
	// rolemenuDescUpdateBy is the schema descriptor for update_by field.
	rolemenuDescUpdateBy := rolemenuMixinFields0[1].Descriptor()
	// rolemenu.DefaultUpdateBy holds the default value on creation for the update_by field.
	rolemenu.DefaultUpdateBy = rolemenuDescUpdateBy.Default.(int64)
	// rolemenuDescCreatedTime is the schema descriptor for created_time field.
	rolemenuDescCreatedTime := rolemenuMixinFields0[2].Descriptor()
	// rolemenu.DefaultCreatedTime holds the default value on creation for the created_time field.
	rolemenu.DefaultCreatedTime = rolemenuDescCreatedTime.Default.(func() time.Time)
	// rolemenuDescUpdatedTime is the schema descriptor for updated_time field.
	rolemenuDescUpdatedTime := rolemenuMixinFields0[3].Descriptor()
	// rolemenu.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	rolemenu.DefaultUpdatedTime = rolemenuDescUpdatedTime.Default.(func() time.Time)
	// rolemenu.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	rolemenu.UpdateDefaultUpdatedTime = rolemenuDescUpdatedTime.UpdateDefault.(func() time.Time)
	storageenvMixin := schema.StorageEnv{}.Mixin()
	storageenvMixinFields0 := storageenvMixin[0].Fields()
	_ = storageenvMixinFields0
	storageenvFields := schema.StorageEnv{}.Fields()
	_ = storageenvFields
	// storageenvDescCreateBy is the schema descriptor for create_by field.
	storageenvDescCreateBy := storageenvMixinFields0[0].Descriptor()
	// storageenv.DefaultCreateBy holds the default value on creation for the create_by field.
	storageenv.DefaultCreateBy = storageenvDescCreateBy.Default.(int64)
	// storageenvDescUpdateBy is the schema descriptor for update_by field.
	storageenvDescUpdateBy := storageenvMixinFields0[1].Descriptor()
	// storageenv.DefaultUpdateBy holds the default value on creation for the update_by field.
	storageenv.DefaultUpdateBy = storageenvDescUpdateBy.Default.(int64)
	// storageenvDescCreatedTime is the schema descriptor for created_time field.
	storageenvDescCreatedTime := storageenvMixinFields0[2].Descriptor()
	// storageenv.DefaultCreatedTime holds the default value on creation for the created_time field.
	storageenv.DefaultCreatedTime = storageenvDescCreatedTime.Default.(func() time.Time)
	// storageenvDescUpdatedTime is the schema descriptor for updated_time field.
	storageenvDescUpdatedTime := storageenvMixinFields0[3].Descriptor()
	// storageenv.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	storageenv.DefaultUpdatedTime = storageenvDescUpdatedTime.Default.(func() time.Time)
	// storageenv.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	storageenv.UpdateDefaultUpdatedTime = storageenvDescUpdatedTime.UpdateDefault.(func() time.Time)
	// storageenvDescName is the schema descriptor for name field.
	storageenvDescName := storageenvFields[1].Descriptor()
	// storageenv.NameValidator is a validator for the "name" field. It is called by the builders before save.
	storageenv.NameValidator = storageenvDescName.Validators[0].(func(string) error)
	// storageenvDescCode is the schema descriptor for code field.
	storageenvDescCode := storageenvFields[2].Descriptor()
	// storageenv.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	storageenv.CodeValidator = storageenvDescCode.Validators[0].(func(string) error)
	// storageenvDescStorageType is the schema descriptor for storage_type field.
	storageenvDescStorageType := storageenvFields[3].Descriptor()
	// storageenv.DefaultStorageType holds the default value on creation for the storage_type field.
	storageenv.DefaultStorageType = storageenvDescStorageType.Default.(string)
	// storageenvDescIsDefault is the schema descriptor for is_default field.
	storageenvDescIsDefault := storageenvFields[4].Descriptor()
	// storageenv.DefaultIsDefault holds the default value on creation for the is_default field.
	storageenv.DefaultIsDefault = storageenvDescIsDefault.Default.(bool)
	// storageenvDescStatus is the schema descriptor for status field.
	storageenvDescStatus := storageenvFields[5].Descriptor()
	// storageenv.DefaultStatus holds the default value on creation for the status field.
	storageenv.DefaultStatus = storageenvDescStatus.Default.(int32)
	// storageenvDescRemark is the schema descriptor for remark field.
	storageenvDescRemark := storageenvFields[7].Descriptor()
	// storageenv.DefaultRemark holds the default value on creation for the remark field.
	storageenv.DefaultRemark = storageenvDescRemark.Default.(string)
	systemconfigMixin := schema.SystemConfig{}.Mixin()
	systemconfigMixinFields0 := systemconfigMixin[0].Fields()
	_ = systemconfigMixinFields0
	systemconfigFields := schema.SystemConfig{}.Fields()
	_ = systemconfigFields
	// systemconfigDescCreateBy is the schema descriptor for create_by field.
	systemconfigDescCreateBy := systemconfigMixinFields0[0].Descriptor()
	// systemconfig.DefaultCreateBy holds the default value on creation for the create_by field.
	systemconfig.DefaultCreateBy = systemconfigDescCreateBy.Default.(int64)
	// systemconfigDescUpdateBy is the schema descriptor for update_by field.
	systemconfigDescUpdateBy := systemconfigMixinFields0[1].Descriptor()
	// systemconfig.DefaultUpdateBy holds the default value on creation for the update_by field.
	systemconfig.DefaultUpdateBy = systemconfigDescUpdateBy.Default.(int64)
	// systemconfigDescCreatedTime is the schema descriptor for created_time field.
	systemconfigDescCreatedTime := systemconfigMixinFields0[2].Descriptor()
	// systemconfig.DefaultCreatedTime holds the default value on creation for the created_time field.
	systemconfig.DefaultCreatedTime = systemconfigDescCreatedTime.Default.(func() time.Time)
	// systemconfigDescUpdatedTime is the schema descriptor for updated_time field.
	systemconfigDescUpdatedTime := systemconfigMixinFields0[3].Descriptor()
	// systemconfig.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	systemconfig.DefaultUpdatedTime = systemconfigDescUpdatedTime.Default.(func() time.Time)
	// systemconfig.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	systemconfig.UpdateDefaultUpdatedTime = systemconfigDescUpdatedTime.UpdateDefault.(func() time.Time)
	// systemconfigDescName is the schema descriptor for name field.
	systemconfigDescName := systemconfigFields[1].Descriptor()
	// systemconfig.NameValidator is a validator for the "name" field. It is called by the builders before save.
	systemconfig.NameValidator = systemconfigDescName.Validators[0].(func(string) error)
	// systemconfigDescCode is the schema descriptor for code field.
	systemconfigDescCode := systemconfigFields[2].Descriptor()
	// systemconfig.CodeValidator is a validator for the "code" field. It is called by the builders before save.
	systemconfig.CodeValidator = systemconfigDescCode.Validators[0].(func(string) error)
	// systemconfigDescRemark is the schema descriptor for remark field.
	systemconfigDescRemark := systemconfigFields[4].Descriptor()
	// systemconfig.DefaultRemark holds the default value on creation for the remark field.
	systemconfig.DefaultRemark = systemconfigDescRemark.Default.(string)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreateBy is the schema descriptor for create_by field.
	userDescCreateBy := userMixinFields0[0].Descriptor()
	// user.DefaultCreateBy holds the default value on creation for the create_by field.
	user.DefaultCreateBy = userDescCreateBy.Default.(int64)
	// userDescUpdateBy is the schema descriptor for update_by field.
	userDescUpdateBy := userMixinFields0[1].Descriptor()
	// user.DefaultUpdateBy holds the default value on creation for the update_by field.
	user.DefaultUpdateBy = userDescUpdateBy.Default.(int64)
	// userDescCreatedTime is the schema descriptor for created_time field.
	userDescCreatedTime := userMixinFields0[2].Descriptor()
	// user.DefaultCreatedTime holds the default value on creation for the created_time field.
	user.DefaultCreatedTime = userDescCreatedTime.Default.(func() time.Time)
	// userDescUpdatedTime is the schema descriptor for updated_time field.
	userDescUpdatedTime := userMixinFields0[3].Descriptor()
	// user.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	user.DefaultUpdatedTime = userDescUpdatedTime.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	user.UpdateDefaultUpdatedTime = userDescUpdatedTime.UpdateDefault.(func() time.Time)
	// userDescUserName is the schema descriptor for user_name field.
	userDescUserName := userFields[1].Descriptor()
	// user.UserNameValidator is a validator for the "user_name" field. It is called by the builders before save.
	user.UserNameValidator = userDescUserName.Validators[0].(func(string) error)
	// userDescNickName is the schema descriptor for nick_name field.
	userDescNickName := userFields[2].Descriptor()
	// user.DefaultNickName holds the default value on creation for the nick_name field.
	user.DefaultNickName = userDescNickName.Default.(string)
	// userDescUserType is the schema descriptor for user_type field.
	userDescUserType := userFields[3].Descriptor()
	// user.DefaultUserType holds the default value on creation for the user_type field.
	user.DefaultUserType = userDescUserType.Default.(int32)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescPhonenumber is the schema descriptor for phonenumber field.
	userDescPhonenumber := userFields[5].Descriptor()
	// user.DefaultPhonenumber holds the default value on creation for the phonenumber field.
	user.DefaultPhonenumber = userDescPhonenumber.Default.(string)
	// userDescSex is the schema descriptor for sex field.
	userDescSex := userFields[6].Descriptor()
	// user.DefaultSex holds the default value on creation for the sex field.
	user.DefaultSex = userDescSex.Default.(int32)
	// userDescAvatar is the schema descriptor for avatar field.
	userDescAvatar := userFields[7].Descriptor()
	// user.DefaultAvatar holds the default value on creation for the avatar field.
	user.DefaultAvatar = userDescAvatar.Default.(string)
	// userDescPassword is the schema descriptor for password field.
	userDescPassword := userFields[8].Descriptor()
	// user.DefaultPassword holds the default value on creation for the password field.
	user.DefaultPassword = userDescPassword.Default.(string)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[9].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int32)
	// userDescSort is the schema descriptor for sort field.
	userDescSort := userFields[10].Descriptor()
	// user.DefaultSort holds the default value on creation for the sort field.
	user.DefaultSort = userDescSort.Default.(int64)
	// userDescLoginIP is the schema descriptor for login_ip field.
	userDescLoginIP := userFields[11].Descriptor()
	// user.DefaultLoginIP holds the default value on creation for the login_ip field.
	user.DefaultLoginIP = userDescLoginIP.Default.(string)
	// userDescLoginDate is the schema descriptor for login_date field.
	userDescLoginDate := userFields[12].Descriptor()
	// user.DefaultLoginDate holds the default value on creation for the login_date field.
	user.DefaultLoginDate = userDescLoginDate.Default.(int64)
	// userDescOpenID is the schema descriptor for open_id field.
	userDescOpenID := userFields[13].Descriptor()
	// user.DefaultOpenID holds the default value on creation for the open_id field.
	user.DefaultOpenID = userDescOpenID.Default.(string)
	// userDescUnionID is the schema descriptor for union_id field.
	userDescUnionID := userFields[14].Descriptor()
	// user.DefaultUnionID holds the default value on creation for the union_id field.
	user.DefaultUnionID = userDescUnionID.Default.(string)
	// userDescRemark is the schema descriptor for remark field.
	userDescRemark := userFields[15].Descriptor()
	// user.DefaultRemark holds the default value on creation for the remark field.
	user.DefaultRemark = userDescRemark.Default.(string)
	userroleMixin := schema.UserRole{}.Mixin()
	userroleMixinFields0 := userroleMixin[0].Fields()
	_ = userroleMixinFields0
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescCreateBy is the schema descriptor for create_by field.
	userroleDescCreateBy := userroleMixinFields0[0].Descriptor()
	// userrole.DefaultCreateBy holds the default value on creation for the create_by field.
	userrole.DefaultCreateBy = userroleDescCreateBy.Default.(int64)
	// userroleDescUpdateBy is the schema descriptor for update_by field.
	userroleDescUpdateBy := userroleMixinFields0[1].Descriptor()
	// userrole.DefaultUpdateBy holds the default value on creation for the update_by field.
	userrole.DefaultUpdateBy = userroleDescUpdateBy.Default.(int64)
	// userroleDescCreatedTime is the schema descriptor for created_time field.
	userroleDescCreatedTime := userroleMixinFields0[2].Descriptor()
	// userrole.DefaultCreatedTime holds the default value on creation for the created_time field.
	userrole.DefaultCreatedTime = userroleDescCreatedTime.Default.(func() time.Time)
	// userroleDescUpdatedTime is the schema descriptor for updated_time field.
	userroleDescUpdatedTime := userroleMixinFields0[3].Descriptor()
	// userrole.DefaultUpdatedTime holds the default value on creation for the updated_time field.
	userrole.DefaultUpdatedTime = userroleDescUpdatedTime.Default.(func() time.Time)
	// userrole.UpdateDefaultUpdatedTime holds the default value on update for the updated_time field.
	userrole.UpdateDefaultUpdatedTime = userroleDescUpdatedTime.UpdateDefault.(func() time.Time)
}
