// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/force-c/nai-tizi/kratos/app/sys-rpc/ent/storageenv"
)

// StorageEnvCreate is the builder for creating a StorageEnv entity.
type StorageEnvCreate struct {
	config
	mutation *StorageEnvMutation
	hooks    []Hook
}

// SetCreateBy sets the "create_by" field.
func (_c *StorageEnvCreate) SetCreateBy(v int64) *StorageEnvCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableCreateBy(v *int64) *StorageEnvCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *StorageEnvCreate) SetUpdateBy(v int64) *StorageEnvCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableUpdateBy(v *int64) *StorageEnvCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetCreatedTime sets the "created_time" field.
func (_c *StorageEnvCreate) SetCreatedTime(v time.Time) *StorageEnvCreate {
	_c.mutation.SetCreatedTime(v)
	return _c
}

// SetNillableCreatedTime sets the "created_time" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableCreatedTime(v *time.Time) *StorageEnvCreate {
	if v != nil {
		_c.SetCreatedTime(*v)
	}
	return _c
}

// SetUpdatedTime sets the "updated_time" field.
func (_c *StorageEnvCreate) SetUpdatedTime(v time.Time) *StorageEnvCreate {
	_c.mutation.SetUpdatedTime(v)
	return _c
}

// SetNillableUpdatedTime sets the "updated_time" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableUpdatedTime(v *time.Time) *StorageEnvCreate {
	if v != nil {
		_c.SetUpdatedTime(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *StorageEnvCreate) SetDeletedAt(v time.Time) *StorageEnvCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableDeletedAt(v *time.Time) *StorageEnvCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *StorageEnvCreate) SetName(v string) *StorageEnvCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *StorageEnvCreate) SetCode(v string) *StorageEnvCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetStorageType sets the "storage_type" field.
func (_c *StorageEnvCreate) SetStorageType(v string) *StorageEnvCreate {
	_c.mutation.SetStorageType(v)
	return _c
}

// SetNillableStorageType sets the "storage_type" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableStorageType(v *string) *StorageEnvCreate {
	if v != nil {
		_c.SetStorageType(*v)
	}
	return _c
}

// SetIsDefault sets the "is_default" field.
func (_c *StorageEnvCreate) SetIsDefault(v bool) *StorageEnvCreate {
	_c.mutation.SetIsDefault(v)
	return _c
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableIsDefault(v *bool) *StorageEnvCreate {
	if v != nil {
		_c.SetIsDefault(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *StorageEnvCreate) SetStatus(v int32) *StorageEnvCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableStatus(v *int32) *StorageEnvCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *StorageEnvCreate) SetConfig(v map[string]interface{}) *StorageEnvCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetRemark sets the "remark" field.
func (_c *StorageEnvCreate) SetRemark(v string) *StorageEnvCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *StorageEnvCreate) SetNillableRemark(v *string) *StorageEnvCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StorageEnvCreate) SetID(v int64) *StorageEnvCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the StorageEnvMutation object of the builder.
func (_c *StorageEnvCreate) Mutation() *StorageEnvMutation {
	return _c.mutation
}

// Save creates the StorageEnv in the database.
func (_c *StorageEnvCreate) Save(ctx context.Context) (*StorageEnv, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StorageEnvCreate) SaveX(ctx context.Context) *StorageEnv {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageEnvCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageEnvCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StorageEnvCreate) defaults() {
	if _, ok := _c.mutation.CreateBy(); !ok {
		v := storageenv.DefaultCreateBy
		_c.mutation.SetCreateBy(v)
	}
	if _, ok := _c.mutation.UpdateBy(); !ok {
		v := storageenv.DefaultUpdateBy
		_c.mutation.SetUpdateBy(v)
	}
	if _, ok := _c.mutation.CreatedTime(); !ok {
		v := storageenv.DefaultCreatedTime()
		_c.mutation.SetCreatedTime(v)
	}
	if _, ok := _c.mutation.UpdatedTime(); !ok {
		v := storageenv.DefaultUpdatedTime()
		_c.mutation.SetUpdatedTime(v)
	}
	if _, ok := _c.mutation.StorageType(); !ok {
		v := storageenv.DefaultStorageType
		_c.mutation.SetStorageType(v)
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		v := storageenv.DefaultIsDefault
		_c.mutation.SetIsDefault(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := storageenv.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Remark(); !ok {
		v := storageenv.DefaultRemark
		_c.mutation.SetRemark(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StorageEnvCreate) check() error {
	if _, ok := _c.mutation.CreateBy(); !ok {
		return &ValidationError{Name: "create_by", err: errors.New(`ent: missing required field "StorageEnv.create_by"`)}
	}
	if _, ok := _c.mutation.UpdateBy(); !ok {
		return &ValidationError{Name: "update_by", err: errors.New(`ent: missing required field "StorageEnv.update_by"`)}
	}
	if _, ok := _c.mutation.CreatedTime(); !ok {
		return &ValidationError{Name: "created_time", err: errors.New(`ent: missing required field "StorageEnv.created_time"`)}
	}
	if _, ok := _c.mutation.UpdatedTime(); !ok {
		return &ValidationError{Name: "updated_time", err: errors.New(`ent: missing required field "StorageEnv.updated_time"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "StorageEnv.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := storageenv.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "StorageEnv.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "StorageEnv.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := storageenv.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "StorageEnv.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StorageType(); !ok {
		return &ValidationError{Name: "storage_type", err: errors.New(`ent: missing required field "StorageEnv.storage_type"`)}
	}
	if _, ok := _c.mutation.IsDefault(); !ok {
		return &ValidationError{Name: "is_default", err: errors.New(`ent: missing required field "StorageEnv.is_default"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StorageEnv.status"`)}
	}
	if _, ok := _c.mutation.Remark(); !ok {
		return &ValidationError{Name: "remark", err: errors.New(`ent: missing required field "StorageEnv.remark"`)}
	}
	return nil
}

func (_c *StorageEnvCreate) sqlSave(ctx context.Context) (*StorageEnv, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StorageEnvCreate) createSpec() (*StorageEnv, *sqlgraph.CreateSpec) {
	var (
		_node = &StorageEnv{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(storageenv.Table, sqlgraph.NewFieldSpec(storageenv.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(storageenv.FieldCreateBy, field.TypeInt64, value)
		_node.CreateBy = value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(storageenv.FieldUpdateBy, field.TypeInt64, value)
		_node.UpdateBy = value
	}
	if value, ok := _c.mutation.CreatedTime(); ok {
		_spec.SetField(storageenv.FieldCreatedTime, field.TypeTime, value)
		_node.CreatedTime = value
	}
	if value, ok := _c.mutation.UpdatedTime(); ok {
		_spec.SetField(storageenv.FieldUpdatedTime, field.TypeTime, value)
		_node.UpdatedTime = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(storageenv.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(storageenv.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(storageenv.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.StorageType(); ok {
		_spec.SetField(storageenv.FieldStorageType, field.TypeString, value)
		_node.StorageType = value
	}
	if value, ok := _c.mutation.IsDefault(); ok {
		_spec.SetField(storageenv.FieldIsDefault, field.TypeBool, value)
		_node.IsDefault = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(storageenv.FieldStatus, field.TypeInt32, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(storageenv.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(storageenv.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	return _node, _spec
}

// StorageEnvCreateBulk is the builder for creating many StorageEnv entities in bulk.
type StorageEnvCreateBulk struct {
	config
	err      error
	builders []*StorageEnvCreate
}

// Save creates the StorageEnv entities in the database.
func (_c *StorageEnvCreateBulk) Save(ctx context.Context) ([]*StorageEnv, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StorageEnv, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StorageEnvMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StorageEnvCreateBulk) SaveX(ctx context.Context) []*StorageEnv {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StorageEnvCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StorageEnvCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
