import type { ReactNode } from 'react';
import type { ComponentType } from 'react';
import {
  ApartmentOutlined,
  ApiOutlined,
  AppstoreOutlined,
  BarsOutlined,
  BookOutlined,
  BugOutlined,
  CloudOutlined,
  CloudServerOutlined,
  CodeOutlined,
  ControlOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EyeOutlined,
  FileOutlined,
  FolderOutlined,
  FormOutlined,
  HomeOutlined,
  KeyOutlined,
  LockOutlined,
  LoginOutlined,
  MonitorOutlined,
  PlusOutlined,
  ReloadOutlined,
  RocketOutlined,
  SafetyOutlined,
  SearchOutlined,
  SettingOutlined,
  TeamOutlined,
  ToolOutlined,
  UploadOutlined,
  UserOutlined,
} from '@ant-design/icons';

const iconNameMap: Record<string, ComponentType> = {
  dashboard: DashboardOutlined,
  home: HomeOutlined,
  setting: SettingOutlined,
  system: SettingOutlined,
  user: UserOutlined,
  peoples: TeamOutlined,
  team: TeamOutlined,
  cloud: CloudOutlined,
  file: FileOutlined,
  upload: UploadOutlined,
  database: DatabaseOutlined,
  dict: BookOutlined,
  monitor: MonitorOutlined,
  login: LoginOutlined,
  logininfor: LoginOutlined,
  form: FormOutlined,
  server: CloudServerOutlined,
  tree: ApartmentOutlined,
  'tree-table': ApartmentOutlined,
  search: SearchOutlined,
  reload: ReloadOutlined,
  download: DownloadOutlined,
  delete: DeleteOutlined,
  plus: PlusOutlined,
  eye: EyeOutlined,
  lock: LockOutlined,
  key: KeyOutlined,
  api: ApiOutlined,
  code: CodeOutlined,
  bug: BugOutlined,
  rocket: RocketOutlined,
  control: ControlOutlined,
  tool: ToolOutlined,
  book: BookOutlined,
  bars: BarsOutlined,
  safety: SafetyOutlined,
  folder: FolderOutlined,
};

export const iconOptions = Object.keys(iconNameMap).map((key) => ({
  label: key,
  value: key,
}));

export function getMenuIconNode(iconName?: string): ReactNode {
  const IconComponent = iconName ? iconNameMap[iconName] : undefined;
  return IconComponent ? <IconComponent /> : <AppstoreOutlined />;
}
