// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: system/v1/attachment.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on AttachmentIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AttachmentIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachmentIdRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AttachmentIdRequestMultiError, or nil if none found.
func (m *AttachmentIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachmentIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AttachmentId

	if len(errors) > 0 {
		return AttachmentIdRequestMultiError(errors)
	}

	return nil
}

// AttachmentIdRequestMultiError is an error wrapping multiple validation
// errors returned by AttachmentIdRequest.ValidateAll() if the designated
// constraints aren't met.
type AttachmentIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachmentIdRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachmentIdRequestMultiError) AllErrors() []error { return m }

// AttachmentIdRequestValidationError is the validation error returned by
// AttachmentIdRequest.Validate if the designated constraints aren't met.
type AttachmentIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachmentIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachmentIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachmentIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachmentIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachmentIdRequestValidationError) ErrorName() string {
	return "AttachmentIdRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AttachmentIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachmentIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachmentIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachmentIdRequestValidationError{}

// Validate checks the field values on UploadFileRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UploadFileRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UploadFileRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UploadFileRequestMultiError, or nil if none found.
func (m *UploadFileRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UploadFileRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FileName

	// no validation rules for FileType

	// no validation rules for Content

	// no validation rules for EnvCode

	if len(errors) > 0 {
		return UploadFileRequestMultiError(errors)
	}

	return nil
}

// UploadFileRequestMultiError is an error wrapping multiple validation errors
// returned by UploadFileRequest.ValidateAll() if the designated constraints
// aren't met.
type UploadFileRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UploadFileRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UploadFileRequestMultiError) AllErrors() []error { return m }

// UploadFileRequestValidationError is the validation error returned by
// UploadFileRequest.Validate if the designated constraints aren't met.
type UploadFileRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UploadFileRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UploadFileRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UploadFileRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UploadFileRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UploadFileRequestValidationError) ErrorName() string {
	return "UploadFileRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UploadFileRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUploadFileRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UploadFileRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UploadFileRequestValidationError{}

// Validate checks the field values on BindAttachmentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *BindAttachmentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BindAttachmentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BindAttachmentRequestMultiError, or nil if none found.
func (m *BindAttachmentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *BindAttachmentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AttachmentId

	// no validation rules for BusinessType

	// no validation rules for BusinessId

	// no validation rules for BusinessField

	// no validation rules for IsPublic

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, BindAttachmentRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, BindAttachmentRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return BindAttachmentRequestValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ExpireTime

	if len(errors) > 0 {
		return BindAttachmentRequestMultiError(errors)
	}

	return nil
}

// BindAttachmentRequestMultiError is an error wrapping multiple validation
// errors returned by BindAttachmentRequest.ValidateAll() if the designated
// constraints aren't met.
type BindAttachmentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BindAttachmentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BindAttachmentRequestMultiError) AllErrors() []error { return m }

// BindAttachmentRequestValidationError is the validation error returned by
// BindAttachmentRequest.Validate if the designated constraints aren't met.
type BindAttachmentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BindAttachmentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BindAttachmentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BindAttachmentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BindAttachmentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BindAttachmentRequestValidationError) ErrorName() string {
	return "BindAttachmentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e BindAttachmentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBindAttachmentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BindAttachmentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BindAttachmentRequestValidationError{}

// Validate checks the field values on ListAttachmentsByBusinessRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ListAttachmentsByBusinessRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAttachmentsByBusinessRequest with
// the rules defined in the proto definition for this message. If any rules
// are violated, the result is a list of violation errors wrapped in
// ListAttachmentsByBusinessRequestMultiError, or nil if none found.
func (m *ListAttachmentsByBusinessRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAttachmentsByBusinessRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for BusinessType

	// no validation rules for BusinessId

	if len(errors) > 0 {
		return ListAttachmentsByBusinessRequestMultiError(errors)
	}

	return nil
}

// ListAttachmentsByBusinessRequestMultiError is an error wrapping multiple
// validation errors returned by
// ListAttachmentsByBusinessRequest.ValidateAll() if the designated
// constraints aren't met.
type ListAttachmentsByBusinessRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAttachmentsByBusinessRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAttachmentsByBusinessRequestMultiError) AllErrors() []error { return m }

// ListAttachmentsByBusinessRequestValidationError is the validation error
// returned by ListAttachmentsByBusinessRequest.Validate if the designated
// constraints aren't met.
type ListAttachmentsByBusinessRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAttachmentsByBusinessRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAttachmentsByBusinessRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAttachmentsByBusinessRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAttachmentsByBusinessRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAttachmentsByBusinessRequestValidationError) ErrorName() string {
	return "ListAttachmentsByBusinessRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAttachmentsByBusinessRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAttachmentsByBusinessRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAttachmentsByBusinessRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAttachmentsByBusinessRequestValidationError{}

// Validate checks the field values on PageAttachmentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageAttachmentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageAttachmentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageAttachmentsRequestMultiError, or nil if none found.
func (m *PageAttachmentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageAttachmentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageNum

	// no validation rules for PageSize

	// no validation rules for FileName

	// no validation rules for FileType

	// no validation rules for BusinessType

	if len(errors) > 0 {
		return PageAttachmentsRequestMultiError(errors)
	}

	return nil
}

// PageAttachmentsRequestMultiError is an error wrapping multiple validation
// errors returned by PageAttachmentsRequest.ValidateAll() if the designated
// constraints aren't met.
type PageAttachmentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageAttachmentsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageAttachmentsRequestMultiError) AllErrors() []error { return m }

// PageAttachmentsRequestValidationError is the validation error returned by
// PageAttachmentsRequest.Validate if the designated constraints aren't met.
type PageAttachmentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageAttachmentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageAttachmentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageAttachmentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageAttachmentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageAttachmentsRequestValidationError) ErrorName() string {
	return "PageAttachmentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PageAttachmentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageAttachmentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageAttachmentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageAttachmentsRequestValidationError{}

// Validate checks the field values on AttachmentURLRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AttachmentURLRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachmentURLRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AttachmentURLRequestMultiError, or nil if none found.
func (m *AttachmentURLRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachmentURLRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AttachmentId

	// no validation rules for Expires

	if len(errors) > 0 {
		return AttachmentURLRequestMultiError(errors)
	}

	return nil
}

// AttachmentURLRequestMultiError is an error wrapping multiple validation
// errors returned by AttachmentURLRequest.ValidateAll() if the designated
// constraints aren't met.
type AttachmentURLRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachmentURLRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachmentURLRequestMultiError) AllErrors() []error { return m }

// AttachmentURLRequestValidationError is the validation error returned by
// AttachmentURLRequest.Validate if the designated constraints aren't met.
type AttachmentURLRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachmentURLRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachmentURLRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachmentURLRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachmentURLRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachmentURLRequestValidationError) ErrorName() string {
	return "AttachmentURLRequestValidationError"
}

// Error satisfies the builtin error interface
func (e AttachmentURLRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachmentURLRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachmentURLRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachmentURLRequestValidationError{}

// Validate checks the field values on AttachmentItem with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AttachmentItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachmentItem with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in AttachmentItemMultiError,
// or nil if none found.
func (m *AttachmentItem) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachmentItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AttachmentId

	// no validation rules for EnvId

	// no validation rules for FileName

	// no validation rules for FileKey

	// no validation rules for FileSize

	// no validation rules for FileType

	// no validation rules for FileExt

	// no validation rules for BusinessType

	// no validation rules for BusinessId

	// no validation rules for BusinessField

	// no validation rules for IsPublic

	// no validation rules for AccessUrl

	// no validation rules for Metadata

	// no validation rules for Status

	// no validation rules for ExpireTime

	// no validation rules for CreateBy

	// no validation rules for CreateTime

	// no validation rules for UpdateTime

	if len(errors) > 0 {
		return AttachmentItemMultiError(errors)
	}

	return nil
}

// AttachmentItemMultiError is an error wrapping multiple validation errors
// returned by AttachmentItem.ValidateAll() if the designated constraints
// aren't met.
type AttachmentItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachmentItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachmentItemMultiError) AllErrors() []error { return m }

// AttachmentItemValidationError is the validation error returned by
// AttachmentItem.Validate if the designated constraints aren't met.
type AttachmentItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachmentItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachmentItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachmentItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachmentItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachmentItemValidationError) ErrorName() string { return "AttachmentItemValidationError" }

// Error satisfies the builtin error interface
func (e AttachmentItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachmentItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachmentItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachmentItemValidationError{}

// Validate checks the field values on AttachmentListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AttachmentListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachmentListReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AttachmentListReplyMultiError, or nil if none found.
func (m *AttachmentListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachmentListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AttachmentListReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AttachmentListReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AttachmentListReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return AttachmentListReplyMultiError(errors)
	}

	return nil
}

// AttachmentListReplyMultiError is an error wrapping multiple validation
// errors returned by AttachmentListReply.ValidateAll() if the designated
// constraints aren't met.
type AttachmentListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachmentListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachmentListReplyMultiError) AllErrors() []error { return m }

// AttachmentListReplyValidationError is the validation error returned by
// AttachmentListReply.Validate if the designated constraints aren't met.
type AttachmentListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachmentListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachmentListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachmentListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachmentListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachmentListReplyValidationError) ErrorName() string {
	return "AttachmentListReplyValidationError"
}

// Error satisfies the builtin error interface
func (e AttachmentListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachmentListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachmentListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachmentListReplyValidationError{}

// Validate checks the field values on PageAttachmentsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PageAttachmentsReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageAttachmentsReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageAttachmentsReplyMultiError, or nil if none found.
func (m *PageAttachmentsReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PageAttachmentsReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageAttachmentsReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageAttachmentsReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageAttachmentsReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	// no validation rules for PageNum

	// no validation rules for PageSize

	if len(errors) > 0 {
		return PageAttachmentsReplyMultiError(errors)
	}

	return nil
}

// PageAttachmentsReplyMultiError is an error wrapping multiple validation
// errors returned by PageAttachmentsReply.ValidateAll() if the designated
// constraints aren't met.
type PageAttachmentsReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageAttachmentsReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageAttachmentsReplyMultiError) AllErrors() []error { return m }

// PageAttachmentsReplyValidationError is the validation error returned by
// PageAttachmentsReply.Validate if the designated constraints aren't met.
type PageAttachmentsReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageAttachmentsReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageAttachmentsReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageAttachmentsReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageAttachmentsReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageAttachmentsReplyValidationError) ErrorName() string {
	return "PageAttachmentsReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PageAttachmentsReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageAttachmentsReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageAttachmentsReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageAttachmentsReplyValidationError{}

// Validate checks the field values on AttachmentURLReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AttachmentURLReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachmentURLReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AttachmentURLReplyMultiError, or nil if none found.
func (m *AttachmentURLReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachmentURLReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AttachmentId

	// no validation rules for Url

	// no validation rules for Expires

	if len(errors) > 0 {
		return AttachmentURLReplyMultiError(errors)
	}

	return nil
}

// AttachmentURLReplyMultiError is an error wrapping multiple validation errors
// returned by AttachmentURLReply.ValidateAll() if the designated constraints
// aren't met.
type AttachmentURLReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachmentURLReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachmentURLReplyMultiError) AllErrors() []error { return m }

// AttachmentURLReplyValidationError is the validation error returned by
// AttachmentURLReply.Validate if the designated constraints aren't met.
type AttachmentURLReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachmentURLReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachmentURLReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachmentURLReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachmentURLReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachmentURLReplyValidationError) ErrorName() string {
	return "AttachmentURLReplyValidationError"
}

// Error satisfies the builtin error interface
func (e AttachmentURLReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachmentURLReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachmentURLReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachmentURLReplyValidationError{}

// Validate checks the field values on AttachmentDownloadReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *AttachmentDownloadReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AttachmentDownloadReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// AttachmentDownloadReplyMultiError, or nil if none found.
func (m *AttachmentDownloadReply) ValidateAll() error {
	return m.validate(true)
}

func (m *AttachmentDownloadReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FileName

	// no validation rules for Content

	if len(errors) > 0 {
		return AttachmentDownloadReplyMultiError(errors)
	}

	return nil
}

// AttachmentDownloadReplyMultiError is an error wrapping multiple validation
// errors returned by AttachmentDownloadReply.ValidateAll() if the designated
// constraints aren't met.
type AttachmentDownloadReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AttachmentDownloadReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AttachmentDownloadReplyMultiError) AllErrors() []error { return m }

// AttachmentDownloadReplyValidationError is the validation error returned by
// AttachmentDownloadReply.Validate if the designated constraints aren't met.
type AttachmentDownloadReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AttachmentDownloadReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AttachmentDownloadReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AttachmentDownloadReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AttachmentDownloadReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AttachmentDownloadReplyValidationError) ErrorName() string {
	return "AttachmentDownloadReplyValidationError"
}

// Error satisfies the builtin error interface
func (e AttachmentDownloadReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAttachmentDownloadReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AttachmentDownloadReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AttachmentDownloadReplyValidationError{}
