// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: system/v1/captcha.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GenerateImageCaptchaRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GenerateImageCaptchaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GenerateImageCaptchaRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GenerateImageCaptchaRequestMultiError, or nil if none found.
func (m *GenerateImageCaptchaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GenerateImageCaptchaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GenerateImageCaptchaRequestMultiError(errors)
	}

	return nil
}

// GenerateImageCaptchaRequestMultiError is an error wrapping multiple
// validation errors returned by GenerateImageCaptchaRequest.ValidateAll() if
// the designated constraints aren't met.
type GenerateImageCaptchaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GenerateImageCaptchaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GenerateImageCaptchaRequestMultiError) AllErrors() []error { return m }

// GenerateImageCaptchaRequestValidationError is the validation error returned
// by GenerateImageCaptchaRequest.Validate if the designated constraints
// aren't met.
type GenerateImageCaptchaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GenerateImageCaptchaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GenerateImageCaptchaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GenerateImageCaptchaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GenerateImageCaptchaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GenerateImageCaptchaRequestValidationError) ErrorName() string {
	return "GenerateImageCaptchaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GenerateImageCaptchaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGenerateImageCaptchaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GenerateImageCaptchaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GenerateImageCaptchaRequestValidationError{}

// Validate checks the field values on CaptchaReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CaptchaReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CaptchaReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CaptchaReplyMultiError, or
// nil if none found.
func (m *CaptchaReply) ValidateAll() error {
	return m.validate(true)
}

func (m *CaptchaReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Type

	if all {
		switch v := interface{}(m.GetData()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CaptchaReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CaptchaReplyValidationError{
					field:  "Data",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetData()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CaptchaReplyValidationError{
				field:  "Data",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for ExpireAt

	if len(errors) > 0 {
		return CaptchaReplyMultiError(errors)
	}

	return nil
}

// CaptchaReplyMultiError is an error wrapping multiple validation errors
// returned by CaptchaReply.ValidateAll() if the designated constraints aren't met.
type CaptchaReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CaptchaReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CaptchaReplyMultiError) AllErrors() []error { return m }

// CaptchaReplyValidationError is the validation error returned by
// CaptchaReply.Validate if the designated constraints aren't met.
type CaptchaReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CaptchaReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CaptchaReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CaptchaReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CaptchaReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CaptchaReplyValidationError) ErrorName() string { return "CaptchaReplyValidationError" }

// Error satisfies the builtin error interface
func (e CaptchaReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCaptchaReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CaptchaReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CaptchaReplyValidationError{}

// Validate checks the field values on SendSMSCaptchaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendSMSCaptchaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendSMSCaptchaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendSMSCaptchaRequestMultiError, or nil if none found.
func (m *SendSMSCaptchaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendSMSCaptchaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Phonenumber

	// no validation rules for Phone

	if len(errors) > 0 {
		return SendSMSCaptchaRequestMultiError(errors)
	}

	return nil
}

// SendSMSCaptchaRequestMultiError is an error wrapping multiple validation
// errors returned by SendSMSCaptchaRequest.ValidateAll() if the designated
// constraints aren't met.
type SendSMSCaptchaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendSMSCaptchaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendSMSCaptchaRequestMultiError) AllErrors() []error { return m }

// SendSMSCaptchaRequestValidationError is the validation error returned by
// SendSMSCaptchaRequest.Validate if the designated constraints aren't met.
type SendSMSCaptchaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendSMSCaptchaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendSMSCaptchaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendSMSCaptchaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendSMSCaptchaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendSMSCaptchaRequestValidationError) ErrorName() string {
	return "SendSMSCaptchaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendSMSCaptchaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendSMSCaptchaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendSMSCaptchaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendSMSCaptchaRequestValidationError{}

// Validate checks the field values on SendEmailCaptchaRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *SendEmailCaptchaRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendEmailCaptchaRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendEmailCaptchaRequestMultiError, or nil if none found.
func (m *SendEmailCaptchaRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendEmailCaptchaRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Email

	if len(errors) > 0 {
		return SendEmailCaptchaRequestMultiError(errors)
	}

	return nil
}

// SendEmailCaptchaRequestMultiError is an error wrapping multiple validation
// errors returned by SendEmailCaptchaRequest.ValidateAll() if the designated
// constraints aren't met.
type SendEmailCaptchaRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendEmailCaptchaRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendEmailCaptchaRequestMultiError) AllErrors() []error { return m }

// SendEmailCaptchaRequestValidationError is the validation error returned by
// SendEmailCaptchaRequest.Validate if the designated constraints aren't met.
type SendEmailCaptchaRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendEmailCaptchaRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendEmailCaptchaRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendEmailCaptchaRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendEmailCaptchaRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendEmailCaptchaRequestValidationError) ErrorName() string {
	return "SendEmailCaptchaRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendEmailCaptchaRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendEmailCaptchaRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendEmailCaptchaRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendEmailCaptchaRequestValidationError{}

// Validate checks the field values on GetEnabledTypesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEnabledTypesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEnabledTypesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEnabledTypesRequestMultiError, or nil if none found.
func (m *GetEnabledTypesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEnabledTypesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetEnabledTypesRequestMultiError(errors)
	}

	return nil
}

// GetEnabledTypesRequestMultiError is an error wrapping multiple validation
// errors returned by GetEnabledTypesRequest.ValidateAll() if the designated
// constraints aren't met.
type GetEnabledTypesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEnabledTypesRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEnabledTypesRequestMultiError) AllErrors() []error { return m }

// GetEnabledTypesRequestValidationError is the validation error returned by
// GetEnabledTypesRequest.Validate if the designated constraints aren't met.
type GetEnabledTypesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEnabledTypesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEnabledTypesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEnabledTypesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEnabledTypesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEnabledTypesRequestValidationError) ErrorName() string {
	return "GetEnabledTypesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetEnabledTypesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEnabledTypesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEnabledTypesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEnabledTypesRequestValidationError{}

// Validate checks the field values on GetEnabledTypesReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetEnabledTypesReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetEnabledTypesReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetEnabledTypesReplyMultiError, or nil if none found.
func (m *GetEnabledTypesReply) ValidateAll() error {
	return m.validate(true)
}

func (m *GetEnabledTypesReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetEnabledTypesReplyMultiError(errors)
	}

	return nil
}

// GetEnabledTypesReplyMultiError is an error wrapping multiple validation
// errors returned by GetEnabledTypesReply.ValidateAll() if the designated
// constraints aren't met.
type GetEnabledTypesReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetEnabledTypesReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetEnabledTypesReplyMultiError) AllErrors() []error { return m }

// GetEnabledTypesReplyValidationError is the validation error returned by
// GetEnabledTypesReply.Validate if the designated constraints aren't met.
type GetEnabledTypesReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetEnabledTypesReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetEnabledTypesReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetEnabledTypesReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetEnabledTypesReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetEnabledTypesReplyValidationError) ErrorName() string {
	return "GetEnabledTypesReplyValidationError"
}

// Error satisfies the builtin error interface
func (e GetEnabledTypesReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetEnabledTypesReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetEnabledTypesReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetEnabledTypesReplyValidationError{}
