// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: api/system/v1/dict.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on DictIdRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DictIdRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictIdRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DictIdRequestMultiError, or
// nil if none found.
func (m *DictIdRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DictIdRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return DictIdRequestMultiError(errors)
	}

	return nil
}

// DictIdRequestMultiError is an error wrapping multiple validation errors
// returned by DictIdRequest.ValidateAll() if the designated constraints
// aren't met.
type DictIdRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictIdRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictIdRequestMultiError) AllErrors() []error { return m }

// DictIdRequestValidationError is the validation error returned by
// DictIdRequest.Validate if the designated constraints aren't met.
type DictIdRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictIdRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictIdRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictIdRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictIdRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictIdRequestValidationError) ErrorName() string { return "DictIdRequestValidationError" }

// Error satisfies the builtin error interface
func (e DictIdRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictIdRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictIdRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictIdRequestValidationError{}

// Validate checks the field values on DictBatchIdsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DictBatchIdsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictBatchIdsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DictBatchIdsRequestMultiError, or nil if none found.
func (m *DictBatchIdsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DictBatchIdsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DictBatchIdsRequestMultiError(errors)
	}

	return nil
}

// DictBatchIdsRequestMultiError is an error wrapping multiple validation
// errors returned by DictBatchIdsRequest.ValidateAll() if the designated
// constraints aren't met.
type DictBatchIdsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictBatchIdsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictBatchIdsRequestMultiError) AllErrors() []error { return m }

// DictBatchIdsRequestValidationError is the validation error returned by
// DictBatchIdsRequest.Validate if the designated constraints aren't met.
type DictBatchIdsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictBatchIdsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictBatchIdsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictBatchIdsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictBatchIdsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictBatchIdsRequestValidationError) ErrorName() string {
	return "DictBatchIdsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DictBatchIdsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictBatchIdsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictBatchIdsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictBatchIdsRequestValidationError{}

// Validate checks the field values on PageDictRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *PageDictRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageDictRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PageDictRequestMultiError, or nil if none found.
func (m *PageDictRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PageDictRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageNum

	// no validation rules for PageSize

	// no validation rules for DictType

	// no validation rules for DictLabel

	if m.Status != nil {
		// no validation rules for Status
	}

	if len(errors) > 0 {
		return PageDictRequestMultiError(errors)
	}

	return nil
}

// PageDictRequestMultiError is an error wrapping multiple validation errors
// returned by PageDictRequest.ValidateAll() if the designated constraints
// aren't met.
type PageDictRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageDictRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageDictRequestMultiError) AllErrors() []error { return m }

// PageDictRequestValidationError is the validation error returned by
// PageDictRequest.Validate if the designated constraints aren't met.
type PageDictRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageDictRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageDictRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageDictRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageDictRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageDictRequestValidationError) ErrorName() string { return "PageDictRequestValidationError" }

// Error satisfies the builtin error interface
func (e PageDictRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageDictRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageDictRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageDictRequestValidationError{}

// Validate checks the field values on GetDictByTypeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDictByTypeRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDictByTypeRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDictByTypeRequestMultiError, or nil if none found.
func (m *GetDictByTypeRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDictByTypeRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DictType

	if m.ParentId != nil {
		// no validation rules for ParentId
	}

	if len(errors) > 0 {
		return GetDictByTypeRequestMultiError(errors)
	}

	return nil
}

// GetDictByTypeRequestMultiError is an error wrapping multiple validation
// errors returned by GetDictByTypeRequest.ValidateAll() if the designated
// constraints aren't met.
type GetDictByTypeRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDictByTypeRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDictByTypeRequestMultiError) AllErrors() []error { return m }

// GetDictByTypeRequestValidationError is the validation error returned by
// GetDictByTypeRequest.Validate if the designated constraints aren't met.
type GetDictByTypeRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDictByTypeRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDictByTypeRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDictByTypeRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDictByTypeRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDictByTypeRequestValidationError) ErrorName() string {
	return "GetDictByTypeRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDictByTypeRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDictByTypeRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDictByTypeRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDictByTypeRequestValidationError{}

// Validate checks the field values on GetDictLabelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetDictLabelRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetDictLabelRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetDictLabelRequestMultiError, or nil if none found.
func (m *GetDictLabelRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetDictLabelRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DictType

	// no validation rules for DictValue

	if len(errors) > 0 {
		return GetDictLabelRequestMultiError(errors)
	}

	return nil
}

// GetDictLabelRequestMultiError is an error wrapping multiple validation
// errors returned by GetDictLabelRequest.ValidateAll() if the designated
// constraints aren't met.
type GetDictLabelRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetDictLabelRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetDictLabelRequestMultiError) AllErrors() []error { return m }

// GetDictLabelRequestValidationError is the validation error returned by
// GetDictLabelRequest.Validate if the designated constraints aren't met.
type GetDictLabelRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetDictLabelRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetDictLabelRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetDictLabelRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetDictLabelRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetDictLabelRequestValidationError) ErrorName() string {
	return "GetDictLabelRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetDictLabelRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetDictLabelRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetDictLabelRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetDictLabelRequestValidationError{}

// Validate checks the field values on DictItem with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DictItem) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictItem with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DictItemMultiError, or nil
// if none found.
func (m *DictItem) ValidateAll() error {
	return m.validate(true)
}

func (m *DictItem) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ParentId

	// no validation rules for DictType

	// no validation rules for DictLabel

	// no validation rules for DictValue

	// no validation rules for Status

	// no validation rules for Sort

	// no validation rules for Remark

	// no validation rules for CreatedTime

	// no validation rules for UpdatedTime

	// no validation rules for IsDefault

	// no validation rules for CreateBy

	// no validation rules for UpdateBy

	if len(errors) > 0 {
		return DictItemMultiError(errors)
	}

	return nil
}

// DictItemMultiError is an error wrapping multiple validation errors returned
// by DictItem.ValidateAll() if the designated constraints aren't met.
type DictItemMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictItemMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictItemMultiError) AllErrors() []error { return m }

// DictItemValidationError is the validation error returned by
// DictItem.Validate if the designated constraints aren't met.
type DictItemValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictItemValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictItemValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictItemValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictItemValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictItemValidationError) ErrorName() string { return "DictItemValidationError" }

// Error satisfies the builtin error interface
func (e DictItemValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictItem.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictItemValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictItemValidationError{}

// Validate checks the field values on UpdateDictRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *UpdateDictRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateDictRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateDictRequestMultiError, or nil if none found.
func (m *UpdateDictRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateDictRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for ParentId

	// no validation rules for DictType

	// no validation rules for DictLabel

	// no validation rules for DictValue

	// no validation rules for Status

	// no validation rules for Sort

	// no validation rules for Remark

	// no validation rules for IsDefault

	if len(errors) > 0 {
		return UpdateDictRequestMultiError(errors)
	}

	return nil
}

// UpdateDictRequestMultiError is an error wrapping multiple validation errors
// returned by UpdateDictRequest.ValidateAll() if the designated constraints
// aren't met.
type UpdateDictRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateDictRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateDictRequestMultiError) AllErrors() []error { return m }

// UpdateDictRequestValidationError is the validation error returned by
// UpdateDictRequest.Validate if the designated constraints aren't met.
type UpdateDictRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateDictRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateDictRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateDictRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateDictRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateDictRequestValidationError) ErrorName() string {
	return "UpdateDictRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateDictRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateDictRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateDictRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateDictRequestValidationError{}

// Validate checks the field values on PageDictReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *PageDictReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PageDictReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in PageDictReplyMultiError, or
// nil if none found.
func (m *PageDictReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PageDictReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetList() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, PageDictReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, PageDictReplyValidationError{
						field:  fmt.Sprintf("List[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return PageDictReplyValidationError{
					field:  fmt.Sprintf("List[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Total

	// no validation rules for PageNum

	// no validation rules for PageSize

	if len(errors) > 0 {
		return PageDictReplyMultiError(errors)
	}

	return nil
}

// PageDictReplyMultiError is an error wrapping multiple validation errors
// returned by PageDictReply.ValidateAll() if the designated constraints
// aren't met.
type PageDictReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PageDictReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PageDictReplyMultiError) AllErrors() []error { return m }

// PageDictReplyValidationError is the validation error returned by
// PageDictReply.Validate if the designated constraints aren't met.
type PageDictReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PageDictReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PageDictReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PageDictReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PageDictReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PageDictReplyValidationError) ErrorName() string { return "PageDictReplyValidationError" }

// Error satisfies the builtin error interface
func (e PageDictReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPageDictReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PageDictReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PageDictReplyValidationError{}

// Validate checks the field values on DictListReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DictListReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictListReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DictListReplyMultiError, or
// nil if none found.
func (m *DictListReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DictListReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetItems() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, DictListReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, DictListReplyValidationError{
						field:  fmt.Sprintf("Items[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return DictListReplyValidationError{
					field:  fmt.Sprintf("Items[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return DictListReplyMultiError(errors)
	}

	return nil
}

// DictListReplyMultiError is an error wrapping multiple validation errors
// returned by DictListReply.ValidateAll() if the designated constraints
// aren't met.
type DictListReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictListReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictListReplyMultiError) AllErrors() []error { return m }

// DictListReplyValidationError is the validation error returned by
// DictListReply.Validate if the designated constraints aren't met.
type DictListReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictListReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictListReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictListReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictListReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictListReplyValidationError) ErrorName() string { return "DictListReplyValidationError" }

// Error satisfies the builtin error interface
func (e DictListReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictListReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictListReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictListReplyValidationError{}

// Validate checks the field values on DictLabelReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *DictLabelReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DictLabelReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in DictLabelReplyMultiError,
// or nil if none found.
func (m *DictLabelReply) ValidateAll() error {
	return m.validate(true)
}

func (m *DictLabelReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Label

	if len(errors) > 0 {
		return DictLabelReplyMultiError(errors)
	}

	return nil
}

// DictLabelReplyMultiError is an error wrapping multiple validation errors
// returned by DictLabelReply.ValidateAll() if the designated constraints
// aren't met.
type DictLabelReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DictLabelReplyMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DictLabelReplyMultiError) AllErrors() []error { return m }

// DictLabelReplyValidationError is the validation error returned by
// DictLabelReply.Validate if the designated constraints aren't met.
type DictLabelReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DictLabelReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DictLabelReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DictLabelReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DictLabelReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DictLabelReplyValidationError) ErrorName() string { return "DictLabelReplyValidationError" }

// Error satisfies the builtin error interface
func (e DictLabelReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDictLabelReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DictLabelReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DictLabelReplyValidationError{}
