// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.19.4
// source: api/system/v1/dict.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DictService_CreateDict_FullMethodName      = "/api.system.v1.DictService/CreateDict"
	DictService_PageDict_FullMethodName        = "/api.system.v1.DictService/PageDict"
	DictService_BatchDeleteDict_FullMethodName = "/api.system.v1.DictService/BatchDeleteDict"
	DictService_GetDictByType_FullMethodName   = "/api.system.v1.DictService/GetDictByType"
	DictService_GetDictLabel_FullMethodName    = "/api.system.v1.DictService/GetDictLabel"
	DictService_UpdateDict_FullMethodName      = "/api.system.v1.DictService/UpdateDict"
	DictService_GetDictById_FullMethodName     = "/api.system.v1.DictService/GetDictById"
	DictService_DeleteDict_FullMethodName      = "/api.system.v1.DictService/DeleteDict"
)

// DictServiceClient is the client API for DictService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DictServiceClient interface {
	CreateDict(ctx context.Context, in *DictItem, opts ...grpc.CallOption) (*MessageReply, error)
	PageDict(ctx context.Context, in *PageDictRequest, opts ...grpc.CallOption) (*PageDictReply, error)
	BatchDeleteDict(ctx context.Context, in *DictBatchIdsRequest, opts ...grpc.CallOption) (*MessageReply, error)
	GetDictByType(ctx context.Context, in *GetDictByTypeRequest, opts ...grpc.CallOption) (*DictListReply, error)
	GetDictLabel(ctx context.Context, in *GetDictLabelRequest, opts ...grpc.CallOption) (*DictLabelReply, error)
	UpdateDict(ctx context.Context, in *UpdateDictRequest, opts ...grpc.CallOption) (*MessageReply, error)
	GetDictById(ctx context.Context, in *DictIdRequest, opts ...grpc.CallOption) (*DictItem, error)
	DeleteDict(ctx context.Context, in *DictIdRequest, opts ...grpc.CallOption) (*MessageReply, error)
}

type dictServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDictServiceClient(cc grpc.ClientConnInterface) DictServiceClient {
	return &dictServiceClient{cc}
}

func (c *dictServiceClient) CreateDict(ctx context.Context, in *DictItem, opts ...grpc.CallOption) (*MessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, DictService_CreateDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) PageDict(ctx context.Context, in *PageDictRequest, opts ...grpc.CallOption) (*PageDictReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageDictReply)
	err := c.cc.Invoke(ctx, DictService_PageDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) BatchDeleteDict(ctx context.Context, in *DictBatchIdsRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, DictService_BatchDeleteDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) GetDictByType(ctx context.Context, in *GetDictByTypeRequest, opts ...grpc.CallOption) (*DictListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictListReply)
	err := c.cc.Invoke(ctx, DictService_GetDictByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) GetDictLabel(ctx context.Context, in *GetDictLabelRequest, opts ...grpc.CallOption) (*DictLabelReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictLabelReply)
	err := c.cc.Invoke(ctx, DictService_GetDictLabel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) UpdateDict(ctx context.Context, in *UpdateDictRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, DictService_UpdateDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) GetDictById(ctx context.Context, in *DictIdRequest, opts ...grpc.CallOption) (*DictItem, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DictItem)
	err := c.cc.Invoke(ctx, DictService_GetDictById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dictServiceClient) DeleteDict(ctx context.Context, in *DictIdRequest, opts ...grpc.CallOption) (*MessageReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MessageReply)
	err := c.cc.Invoke(ctx, DictService_DeleteDict_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DictServiceServer is the server API for DictService service.
// All implementations must embed UnimplementedDictServiceServer
// for forward compatibility.
type DictServiceServer interface {
	CreateDict(context.Context, *DictItem) (*MessageReply, error)
	PageDict(context.Context, *PageDictRequest) (*PageDictReply, error)
	BatchDeleteDict(context.Context, *DictBatchIdsRequest) (*MessageReply, error)
	GetDictByType(context.Context, *GetDictByTypeRequest) (*DictListReply, error)
	GetDictLabel(context.Context, *GetDictLabelRequest) (*DictLabelReply, error)
	UpdateDict(context.Context, *UpdateDictRequest) (*MessageReply, error)
	GetDictById(context.Context, *DictIdRequest) (*DictItem, error)
	DeleteDict(context.Context, *DictIdRequest) (*MessageReply, error)
	mustEmbedUnimplementedDictServiceServer()
}

// UnimplementedDictServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDictServiceServer struct{}

func (UnimplementedDictServiceServer) CreateDict(context.Context, *DictItem) (*MessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDict not implemented")
}
func (UnimplementedDictServiceServer) PageDict(context.Context, *PageDictRequest) (*PageDictReply, error) {
	return nil, status.Error(codes.Unimplemented, "method PageDict not implemented")
}
func (UnimplementedDictServiceServer) BatchDeleteDict(context.Context, *DictBatchIdsRequest) (*MessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDeleteDict not implemented")
}
func (UnimplementedDictServiceServer) GetDictByType(context.Context, *GetDictByTypeRequest) (*DictListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDictByType not implemented")
}
func (UnimplementedDictServiceServer) GetDictLabel(context.Context, *GetDictLabelRequest) (*DictLabelReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDictLabel not implemented")
}
func (UnimplementedDictServiceServer) UpdateDict(context.Context, *UpdateDictRequest) (*MessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDict not implemented")
}
func (UnimplementedDictServiceServer) GetDictById(context.Context, *DictIdRequest) (*DictItem, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDictById not implemented")
}
func (UnimplementedDictServiceServer) DeleteDict(context.Context, *DictIdRequest) (*MessageReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteDict not implemented")
}
func (UnimplementedDictServiceServer) mustEmbedUnimplementedDictServiceServer() {}
func (UnimplementedDictServiceServer) testEmbeddedByValue()                     {}

// UnsafeDictServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DictServiceServer will
// result in compilation errors.
type UnsafeDictServiceServer interface {
	mustEmbedUnimplementedDictServiceServer()
}

func RegisterDictServiceServer(s grpc.ServiceRegistrar, srv DictServiceServer) {
	// If the following call panics, it indicates UnimplementedDictServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DictService_ServiceDesc, srv)
}

func _DictService_CreateDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictItem)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).CreateDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_CreateDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).CreateDict(ctx, req.(*DictItem))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_PageDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageDictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).PageDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_PageDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).PageDict(ctx, req.(*PageDictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_BatchDeleteDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictBatchIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).BatchDeleteDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_BatchDeleteDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).BatchDeleteDict(ctx, req.(*DictBatchIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_GetDictByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDictByTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).GetDictByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_GetDictByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).GetDictByType(ctx, req.(*GetDictByTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_GetDictLabel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDictLabelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).GetDictLabel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_GetDictLabel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).GetDictLabel(ctx, req.(*GetDictLabelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_UpdateDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).UpdateDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_UpdateDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).UpdateDict(ctx, req.(*UpdateDictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_GetDictById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).GetDictById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_GetDictById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).GetDictById(ctx, req.(*DictIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DictService_DeleteDict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DictIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DictServiceServer).DeleteDict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DictService_DeleteDict_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DictServiceServer).DeleteDict(ctx, req.(*DictIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DictService_ServiceDesc is the grpc.ServiceDesc for DictService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DictService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.system.v1.DictService",
	HandlerType: (*DictServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDict",
			Handler:    _DictService_CreateDict_Handler,
		},
		{
			MethodName: "PageDict",
			Handler:    _DictService_PageDict_Handler,
		},
		{
			MethodName: "BatchDeleteDict",
			Handler:    _DictService_BatchDeleteDict_Handler,
		},
		{
			MethodName: "GetDictByType",
			Handler:    _DictService_GetDictByType_Handler,
		},
		{
			MethodName: "GetDictLabel",
			Handler:    _DictService_GetDictLabel_Handler,
		},
		{
			MethodName: "UpdateDict",
			Handler:    _DictService_UpdateDict_Handler,
		},
		{
			MethodName: "GetDictById",
			Handler:    _DictService_GetDictById_Handler,
		},
		{
			MethodName: "DeleteDict",
			Handler:    _DictService_DeleteDict_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/system/v1/dict.proto",
}
