// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: system/v1/storage.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StorageEmpty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageEmpty) Reset() {
	*x = StorageEmpty{}
	mi := &file_system_v1_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageEmpty) ProtoMessage() {}

func (x *StorageEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageEmpty.ProtoReflect.Descriptor instead.
func (*StorageEmpty) Descriptor() ([]byte, []int) {
	return file_system_v1_storage_proto_rawDescGZIP(), []int{0}
}

type StorageIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageIdRequest) Reset() {
	*x = StorageIdRequest{}
	mi := &file_system_v1_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageIdRequest) ProtoMessage() {}

func (x *StorageIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageIdRequest.ProtoReflect.Descriptor instead.
func (*StorageIdRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StorageIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StorageEnvItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	StorageType   string                 `protobuf:"bytes,4,opt,name=storageType,proto3" json:"storageType,omitempty"`
	IsDefault     bool                   `protobuf:"varint,5,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedTime   string                 `protobuf:"bytes,7,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	UpdatedTime   string                 `protobuf:"bytes,8,opt,name=updatedTime,proto3" json:"updatedTime,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,9,opt,name=config,proto3" json:"config,omitempty"`
	Remark        string                 `protobuf:"bytes,10,opt,name=remark,proto3" json:"remark,omitempty"`
	CreateBy      int64                  `protobuf:"varint,11,opt,name=createBy,proto3" json:"createBy,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,12,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageEnvItem) Reset() {
	*x = StorageEnvItem{}
	mi := &file_system_v1_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageEnvItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageEnvItem) ProtoMessage() {}

func (x *StorageEnvItem) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageEnvItem.ProtoReflect.Descriptor instead.
func (*StorageEnvItem) Descriptor() ([]byte, []int) {
	return file_system_v1_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StorageEnvItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StorageEnvItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StorageEnvItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StorageEnvItem) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *StorageEnvItem) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *StorageEnvItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StorageEnvItem) GetCreatedTime() string {
	if x != nil {
		return x.CreatedTime
	}
	return ""
}

func (x *StorageEnvItem) GetUpdatedTime() string {
	if x != nil {
		return x.UpdatedTime
	}
	return ""
}

func (x *StorageEnvItem) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StorageEnvItem) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *StorageEnvItem) GetCreateBy() int64 {
	if x != nil {
		return x.CreateBy
	}
	return 0
}

func (x *StorageEnvItem) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type PageStorageEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StorageType   string                 `protobuf:"bytes,4,opt,name=storageType,proto3" json:"storageType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageStorageEnvRequest) Reset() {
	*x = PageStorageEnvRequest{}
	mi := &file_system_v1_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageStorageEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageStorageEnvRequest) ProtoMessage() {}

func (x *PageStorageEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageStorageEnvRequest.ProtoReflect.Descriptor instead.
func (*PageStorageEnvRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_storage_proto_rawDescGZIP(), []int{3}
}

func (x *PageStorageEnvRequest) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *PageStorageEnvRequest) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageStorageEnvRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PageStorageEnvRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

type SetDefaultStorageEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetDefaultStorageEnvRequest) Reset() {
	*x = SetDefaultStorageEnvRequest{}
	mi := &file_system_v1_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetDefaultStorageEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetDefaultStorageEnvRequest) ProtoMessage() {}

func (x *SetDefaultStorageEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetDefaultStorageEnvRequest.ProtoReflect.Descriptor instead.
func (*SetDefaultStorageEnvRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_storage_proto_rawDescGZIP(), []int{4}
}

func (x *SetDefaultStorageEnvRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateStorageEnvRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	StorageType   string                 `protobuf:"bytes,4,opt,name=storageType,proto3" json:"storageType,omitempty"`
	IsDefault     bool                   `protobuf:"varint,5,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Status        int32                  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Config        *structpb.Struct       `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	Remark        string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	UpdateBy      int64                  `protobuf:"varint,9,opt,name=updateBy,proto3" json:"updateBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStorageEnvRequest) Reset() {
	*x = UpdateStorageEnvRequest{}
	mi := &file_system_v1_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageEnvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageEnvRequest) ProtoMessage() {}

func (x *UpdateStorageEnvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageEnvRequest.ProtoReflect.Descriptor instead.
func (*UpdateStorageEnvRequest) Descriptor() ([]byte, []int) {
	return file_system_v1_storage_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateStorageEnvRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateStorageEnvRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateStorageEnvRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UpdateStorageEnvRequest) GetStorageType() string {
	if x != nil {
		return x.StorageType
	}
	return ""
}

func (x *UpdateStorageEnvRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *UpdateStorageEnvRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateStorageEnvRequest) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateStorageEnvRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *UpdateStorageEnvRequest) GetUpdateBy() int64 {
	if x != nil {
		return x.UpdateBy
	}
	return 0
}

type PageStorageEnvReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*StorageEnvItem      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	PageNum       int64                  `protobuf:"varint,3,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageStorageEnvReply) Reset() {
	*x = PageStorageEnvReply{}
	mi := &file_system_v1_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageStorageEnvReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageStorageEnvReply) ProtoMessage() {}

func (x *PageStorageEnvReply) ProtoReflect() protoreflect.Message {
	mi := &file_system_v1_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageStorageEnvReply.ProtoReflect.Descriptor instead.
func (*PageStorageEnvReply) Descriptor() ([]byte, []int) {
	return file_system_v1_storage_proto_rawDescGZIP(), []int{6}
}

func (x *PageStorageEnvReply) GetList() []*StorageEnvItem {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *PageStorageEnvReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PageStorageEnvReply) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *PageStorageEnvReply) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_system_v1_storage_proto protoreflect.FileDescriptor

const file_system_v1_storage_proto_rawDesc = "" +
	"\n" +
	"\x17system/v1/storage.proto\x12\rapi.system.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x14system/v1/auth.proto\"\x0e\n" +
	"\fStorageEmpty\"\"\n" +
	"\x10StorageIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe5\x02\n" +
	"\x0eStorageEnvItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vstorageType\x18\x04 \x01(\tR\vstorageType\x12\x1c\n" +
	"\tisDefault\x18\x05 \x01(\bR\tisDefault\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12 \n" +
	"\vcreatedTime\x18\a \x01(\tR\vcreatedTime\x12 \n" +
	"\vupdatedTime\x18\b \x01(\tR\vupdatedTime\x12/\n" +
	"\x06config\x18\t \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x16\n" +
	"\x06remark\x18\n" +
	" \x01(\tR\x06remark\x12\x1a\n" +
	"\bcreateBy\x18\v \x01(\x03R\bcreateBy\x12\x1a\n" +
	"\bupdateBy\x18\f \x01(\x03R\bupdateBy\"\x83\x01\n" +
	"\x15PageStorageEnvRequest\x12\x18\n" +
	"\apageNum\x18\x01 \x01(\x03R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vstorageType\x18\x04 \x01(\tR\vstorageType\"-\n" +
	"\x1bSetDefaultStorageEnvRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x8e\x02\n" +
	"\x17UpdateStorageEnvRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12 \n" +
	"\vstorageType\x18\x04 \x01(\tR\vstorageType\x12\x1c\n" +
	"\tisDefault\x18\x05 \x01(\bR\tisDefault\x12\x16\n" +
	"\x06status\x18\x06 \x01(\x05R\x06status\x12/\n" +
	"\x06config\x18\a \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\x12\x1a\n" +
	"\bupdateBy\x18\t \x01(\x03R\bupdateBy\"\x94\x01\n" +
	"\x13PageStorageEnvReply\x121\n" +
	"\x04list\x18\x01 \x03(\v2\x1d.api.system.v1.StorageEnvItemR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x18\n" +
	"\apageNum\x18\x03 \x01(\x03R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize2\xf3\a\n" +
	"\x11StorageEnvService\x12p\n" +
	"\x10CreateStorageEnv\x12\x1d.api.system.v1.StorageEnvItem\x1a\x1d.api.system.v1.StorageEnvItem\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/storage-env\x12\x7f\n" +
	"\x0ePageStorageEnv\x12$.api.system.v1.PageStorageEnvRequest\x1a\".api.system.v1.PageStorageEnvReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v1/storage-env/page\x12w\n" +
	"\x14GetDefaultStorageEnv\x12\x1b.api.system.v1.StorageEmpty\x1a\x1d.api.system.v1.StorageEnvItem\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/storage-env/default\x12\x87\x01\n" +
	"\x14SetDefaultStorageEnv\x12*.api.system.v1.SetDefaultStorageEnvRequest\x1a\x1b.api.system.v1.MessageReply\"&\x82\xd3\xe4\x93\x02 :\x01*\"\x1b/api/v1/storage-env/default\x12|\n" +
	"\x10UpdateStorageEnv\x12&.api.system.v1.UpdateStorageEnvRequest\x1a\x1b.api.system.v1.MessageReply\"#\x82\xd3\xe4\x93\x02\x1d:\x01*\x1a\x18/api/v1/storage-env/{id}\x12q\n" +
	"\rGetStorageEnv\x12\x1f.api.system.v1.StorageIdRequest\x1a\x1d.api.system.v1.StorageEnvItem\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/storage-env/{id}\x12\x82\x01\n" +
	"\x18TestStorageEnvConnection\x12\x1f.api.system.v1.StorageIdRequest\x1a\x1b.api.system.v1.MessageReply\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/api/v1/storage-env/{id}/test\x12r\n" +
	"\x10DeleteStorageEnv\x12\x1f.api.system.v1.StorageIdRequest\x1a\x1b.api.system.v1.MessageReply\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/storage-env/{id}B4Z2github.com/gcc798/nai-tizi/kratos/api/system/v1;v1b\x06proto3"

var (
	file_system_v1_storage_proto_rawDescOnce sync.Once
	file_system_v1_storage_proto_rawDescData []byte
)

func file_system_v1_storage_proto_rawDescGZIP() []byte {
	file_system_v1_storage_proto_rawDescOnce.Do(func() {
		file_system_v1_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_system_v1_storage_proto_rawDesc), len(file_system_v1_storage_proto_rawDesc)))
	})
	return file_system_v1_storage_proto_rawDescData
}

var file_system_v1_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_system_v1_storage_proto_goTypes = []any{
	(*StorageEmpty)(nil),                // 0: api.system.v1.StorageEmpty
	(*StorageIdRequest)(nil),            // 1: api.system.v1.StorageIdRequest
	(*StorageEnvItem)(nil),              // 2: api.system.v1.StorageEnvItem
	(*PageStorageEnvRequest)(nil),       // 3: api.system.v1.PageStorageEnvRequest
	(*SetDefaultStorageEnvRequest)(nil), // 4: api.system.v1.SetDefaultStorageEnvRequest
	(*UpdateStorageEnvRequest)(nil),     // 5: api.system.v1.UpdateStorageEnvRequest
	(*PageStorageEnvReply)(nil),         // 6: api.system.v1.PageStorageEnvReply
	(*structpb.Struct)(nil),             // 7: google.protobuf.Struct
	(*MessageReply)(nil),                // 8: api.system.v1.MessageReply
}
var file_system_v1_storage_proto_depIdxs = []int32{
	7,  // 0: api.system.v1.StorageEnvItem.config:type_name -> google.protobuf.Struct
	7,  // 1: api.system.v1.UpdateStorageEnvRequest.config:type_name -> google.protobuf.Struct
	2,  // 2: api.system.v1.PageStorageEnvReply.list:type_name -> api.system.v1.StorageEnvItem
	2,  // 3: api.system.v1.StorageEnvService.CreateStorageEnv:input_type -> api.system.v1.StorageEnvItem
	3,  // 4: api.system.v1.StorageEnvService.PageStorageEnv:input_type -> api.system.v1.PageStorageEnvRequest
	0,  // 5: api.system.v1.StorageEnvService.GetDefaultStorageEnv:input_type -> api.system.v1.StorageEmpty
	4,  // 6: api.system.v1.StorageEnvService.SetDefaultStorageEnv:input_type -> api.system.v1.SetDefaultStorageEnvRequest
	5,  // 7: api.system.v1.StorageEnvService.UpdateStorageEnv:input_type -> api.system.v1.UpdateStorageEnvRequest
	1,  // 8: api.system.v1.StorageEnvService.GetStorageEnv:input_type -> api.system.v1.StorageIdRequest
	1,  // 9: api.system.v1.StorageEnvService.TestStorageEnvConnection:input_type -> api.system.v1.StorageIdRequest
	1,  // 10: api.system.v1.StorageEnvService.DeleteStorageEnv:input_type -> api.system.v1.StorageIdRequest
	2,  // 11: api.system.v1.StorageEnvService.CreateStorageEnv:output_type -> api.system.v1.StorageEnvItem
	6,  // 12: api.system.v1.StorageEnvService.PageStorageEnv:output_type -> api.system.v1.PageStorageEnvReply
	2,  // 13: api.system.v1.StorageEnvService.GetDefaultStorageEnv:output_type -> api.system.v1.StorageEnvItem
	8,  // 14: api.system.v1.StorageEnvService.SetDefaultStorageEnv:output_type -> api.system.v1.MessageReply
	8,  // 15: api.system.v1.StorageEnvService.UpdateStorageEnv:output_type -> api.system.v1.MessageReply
	2,  // 16: api.system.v1.StorageEnvService.GetStorageEnv:output_type -> api.system.v1.StorageEnvItem
	8,  // 17: api.system.v1.StorageEnvService.TestStorageEnvConnection:output_type -> api.system.v1.MessageReply
	8,  // 18: api.system.v1.StorageEnvService.DeleteStorageEnv:output_type -> api.system.v1.MessageReply
	11, // [11:19] is the sub-list for method output_type
	3,  // [3:11] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_system_v1_storage_proto_init() }
func file_system_v1_storage_proto_init() {
	if File_system_v1_storage_proto != nil {
		return
	}
	file_system_v1_auth_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_system_v1_storage_proto_rawDesc), len(file_system_v1_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_system_v1_storage_proto_goTypes,
		DependencyIndexes: file_system_v1_storage_proto_depIdxs,
		MessageInfos:      file_system_v1_storage_proto_msgTypes,
	}.Build()
	File_system_v1_storage_proto = out.File
	file_system_v1_storage_proto_goTypes = nil
	file_system_v1_storage_proto_depIdxs = nil
}
