// Code generated by ent, DO NOT EDIT.

package dictdata

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the dictdata type in the database.
	Label = "dict_data"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldUpdateBy holds the string denoting the update_by field in the database.
	FieldUpdateBy = "update_by"
	// FieldCreatedTime holds the string denoting the created_time field in the database.
	FieldCreatedTime = "created_time"
	// FieldUpdatedTime holds the string denoting the updated_time field in the database.
	FieldUpdatedTime = "updated_time"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldParentID holds the string denoting the parent_id field in the database.
	FieldParentID = "parent_id"
	// FieldSort holds the string denoting the sort field in the database.
	FieldSort = "sort"
	// FieldDictLabel holds the string denoting the dict_label field in the database.
	FieldDictLabel = "dict_label"
	// FieldDictValue holds the string denoting the dict_value field in the database.
	FieldDictValue = "dict_value"
	// FieldDictType holds the string denoting the dict_type field in the database.
	FieldDictType = "dict_type"
	// FieldIsDefault holds the string denoting the is_default field in the database.
	FieldIsDefault = "is_default"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// Table holds the table name of the dictdata in the database.
	Table = "s_dict_data"
)

// Columns holds all SQL columns for dictdata fields.
var Columns = []string{
	FieldID,
	FieldCreateBy,
	FieldUpdateBy,
	FieldCreatedTime,
	FieldUpdatedTime,
	FieldDeletedAt,
	FieldParentID,
	FieldSort,
	FieldDictLabel,
	FieldDictValue,
	FieldDictType,
	FieldIsDefault,
	FieldStatus,
	FieldRemark,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateBy holds the default value on creation for the "create_by" field.
	DefaultCreateBy int64
	// DefaultUpdateBy holds the default value on creation for the "update_by" field.
	DefaultUpdateBy int64
	// DefaultCreatedTime holds the default value on creation for the "created_time" field.
	DefaultCreatedTime func() time.Time
	// DefaultUpdatedTime holds the default value on creation for the "updated_time" field.
	DefaultUpdatedTime func() time.Time
	// UpdateDefaultUpdatedTime holds the default value on update for the "updated_time" field.
	UpdateDefaultUpdatedTime func() time.Time
	// DefaultParentID holds the default value on creation for the "parent_id" field.
	DefaultParentID int64
	// DefaultSort holds the default value on creation for the "sort" field.
	DefaultSort int64
	// DefaultDictLabel holds the default value on creation for the "dict_label" field.
	DefaultDictLabel string
	// DefaultDictValue holds the default value on creation for the "dict_value" field.
	DefaultDictValue string
	// DefaultDictType holds the default value on creation for the "dict_type" field.
	DefaultDictType string
	// DefaultIsDefault holds the default value on creation for the "is_default" field.
	DefaultIsDefault bool
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus int32
	// DefaultRemark holds the default value on creation for the "remark" field.
	DefaultRemark string
)

// OrderOption defines the ordering options for the DictData queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByUpdateBy orders the results by the update_by field.
func ByUpdateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateBy, opts...).ToFunc()
}

// ByCreatedTime orders the results by the created_time field.
func ByCreatedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedTime, opts...).ToFunc()
}

// ByUpdatedTime orders the results by the updated_time field.
func ByUpdatedTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedTime, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByParentID orders the results by the parent_id field.
func ByParentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParentID, opts...).ToFunc()
}

// BySort orders the results by the sort field.
func BySort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSort, opts...).ToFunc()
}

// ByDictLabel orders the results by the dict_label field.
func ByDictLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDictLabel, opts...).ToFunc()
}

// ByDictValue orders the results by the dict_value field.
func ByDictValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDictValue, opts...).ToFunc()
}

// ByDictType orders the results by the dict_type field.
func ByDictType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDictType, opts...).ToFunc()
}

// ByIsDefault orders the results by the is_default field.
func ByIsDefault(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDefault, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}
